// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: event_name.proto
// Protobuf C++ Version: 6.32.0

#include "event_name.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace Event {

inline constexpr RoomStatusRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        game_started_{false} {}

template <typename>
PROTOBUF_CONSTEXPR RoomStatusRequest::RoomStatusRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(RoomStatusRequest_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct RoomStatusRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RoomStatusRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RoomStatusRequestDefaultTypeInternal() {}
  union {
    RoomStatusRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RoomStatusRequestDefaultTypeInternal _RoomStatusRequest_default_instance_;

inline constexpr Player::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        uniqueid_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()) {}

template <typename>
PROTOBUF_CONSTEXPR Player::Player(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(Player_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct PlayerDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PlayerDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PlayerDefaultTypeInternal() {}
  union {
    Player _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PlayerDefaultTypeInternal _Player_default_instance_;

inline constexpr JoinRoomRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        room_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()) {}

template <typename>
PROTOBUF_CONSTEXPR JoinRoomRequest::JoinRoomRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(JoinRoomRequest_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct JoinRoomRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR JoinRoomRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~JoinRoomRequestDefaultTypeInternal() {}
  union {
    JoinRoomRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 JoinRoomRequestDefaultTypeInternal _JoinRoomRequest_default_instance_;

inline constexpr JoinRoomResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        player_in_room_{},
        room_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        uniqueid_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()) {}

template <typename>
PROTOBUF_CONSTEXPR JoinRoomResponse::JoinRoomResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(JoinRoomResponse_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct JoinRoomResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR JoinRoomResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~JoinRoomResponseDefaultTypeInternal() {}
  union {
    JoinRoomResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 JoinRoomResponseDefaultTypeInternal _JoinRoomResponse_default_instance_;

inline constexpr Event::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : Data_Event_{},
        _cached_size_{0},
        _oneof_case_{} {}

template <typename>
PROTOBUF_CONSTEXPR Event::Event(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(Event_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct EventDefaultTypeInternal {
  PROTOBUF_CONSTEXPR EventDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~EventDefaultTypeInternal() {}
  union {
    Event _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 EventDefaultTypeInternal _Event_default_instance_;
}  // namespace Event
static constexpr const ::_pb::EnumDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_enum_descriptors_event_5fname_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_service_descriptors_event_5fname_2eproto = nullptr;
const ::uint32_t
    TableStruct_event_5fname_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::Event::Player, _impl_._has_bits_),
        4, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::Event::Player, _impl_.uniqueid_),
        0,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::Event::JoinRoomRequest, _impl_._has_bits_),
        4, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::Event::JoinRoomRequest, _impl_.room_),
        0,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::Event::JoinRoomResponse, _impl_._has_bits_),
        6, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::Event::JoinRoomResponse, _impl_.room_),
        PROTOBUF_FIELD_OFFSET(::Event::JoinRoomResponse, _impl_.uniqueid_),
        PROTOBUF_FIELD_OFFSET(::Event::JoinRoomResponse, _impl_.player_in_room_),
        0,
        1,
        ~0u,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::Event::RoomStatusRequest, _impl_._has_bits_),
        4, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::Event::RoomStatusRequest, _impl_.game_started_),
        0,
        0x004, // bitmap
        PROTOBUF_FIELD_OFFSET(::Event::Event, _impl_._oneof_case_[0]),
        PROTOBUF_FIELD_OFFSET(::Event::Event, _impl_.Data_Event_),
        PROTOBUF_FIELD_OFFSET(::Event::Event, _impl_.Data_Event_),
        PROTOBUF_FIELD_OFFSET(::Event::Event, _impl_.Data_Event_),
        PROTOBUF_FIELD_OFFSET(::Event::Event, _impl_.Data_Event_),
        PROTOBUF_FIELD_OFFSET(::Event::Event, _impl_.Data_Event_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::Event::Player)},
        {5, sizeof(::Event::JoinRoomRequest)},
        {10, sizeof(::Event::JoinRoomResponse)},
        {19, sizeof(::Event::RoomStatusRequest)},
        {24, sizeof(::Event::Event)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::Event::_Player_default_instance_._instance,
    &::Event::_JoinRoomRequest_default_instance_._instance,
    &::Event::_JoinRoomResponse_default_instance_._instance,
    &::Event::_RoomStatusRequest_default_instance_._instance,
    &::Event::_Event_default_instance_._instance,
};
const char descriptor_table_protodef_event_5fname_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\020event_name.proto\022\005Event\"\032\n\006Player\022\020\n\010u"
    "niqueID\030\001 \001(\t\"\037\n\017JoinRoomRequest\022\014\n\004room"
    "\030\001 \001(\t\"Y\n\020JoinRoomResponse\022\014\n\004room\030\001 \001(\t"
    "\022\020\n\010uniqueID\030\002 \001(\t\022%\n\016player_in_room\030\003 \003"
    "(\0132\r.Event.Player\")\n\021RoomStatusRequest\022\024"
    "\n\014game_started\030\001 \001(\010\"\340\001\n\005Event\022$\n\013player"
    "_data\030\001 \001(\0132\r.Event.PlayerH\000\0223\n\021join_roo"
    "m_request\030\002 \001(\0132\026.Event.JoinRoomRequestH"
    "\000\0225\n\022join_room_response\030\003 \001(\0132\027.Event.Jo"
    "inRoomResponseH\000\0227\n\023room_status_request\030"
    "\004 \001(\0132\030.Event.RoomStatusRequestH\000B\014\n\nDat"
    "a_EventB\nZ\010/gatewayb\006proto3"
};
static ::absl::once_flag descriptor_table_event_5fname_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_event_5fname_2eproto = {
    false,
    false,
    467,
    descriptor_table_protodef_event_5fname_2eproto,
    "event_name.proto",
    &descriptor_table_event_5fname_2eproto_once,
    nullptr,
    0,
    5,
    schemas,
    file_default_instances,
    TableStruct_event_5fname_2eproto::offsets,
    file_level_enum_descriptors_event_5fname_2eproto,
    file_level_service_descriptors_event_5fname_2eproto,
};
namespace Event {
// ===================================================================

class Player::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<Player>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(Player, _impl_._has_bits_);
};

Player::Player(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Player_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Event.Player)
}
PROTOBUF_NDEBUG_INLINE Player::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::Event::Player& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        uniqueid_(arena, from.uniqueid_) {}

Player::Player(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const Player& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Player_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Player* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:Event.Player)
}
PROTOBUF_NDEBUG_INLINE Player::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        uniqueid_(arena) {}

inline void Player::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
Player::~Player() {
  // @@protoc_insertion_point(destructor:Event.Player)
  SharedDtor(*this);
}
inline void Player::SharedDtor(MessageLite& self) {
  Player& this_ = static_cast<Player&>(self);
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    this_.VerifyHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.uniqueid_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL Player::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) Player(arena);
}
constexpr auto Player::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(Player),
                                            alignof(Player));
}
constexpr auto Player::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_Player_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &Player::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<Player>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &Player::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<Player>(), &Player::ByteSizeLong,
              &Player::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(Player, _impl_._cached_size_),
          false,
      },
      &Player::kDescriptorMethods,
      &descriptor_table_event_5fname_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull Player_class_data_ =
        Player::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
Player::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&Player_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(Player_class_data_.tc_table);
  return Player_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 29, 2>
Player::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Player, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    Player_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Event::Player>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string uniqueID = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(Player, _impl_.uniqueid_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string uniqueID = 1;
    {PROTOBUF_FIELD_OFFSET(Player, _impl_.uniqueid_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\14\10\0\0\0\0\0\0"
    "Event.Player"
    "uniqueID"
  }},
};
PROTOBUF_NOINLINE void Player::Clear() {
// @@protoc_insertion_point(message_clear_start:Event.Player)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001U) != 0) {
    _impl_.uniqueid_.ClearNonDefaultToEmpty();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL Player::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const Player& this_ = static_cast<const Player&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL Player::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const Player& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    this_.VerifyHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:Event.Player)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string uniqueID = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000001U) != 0) {
    if (!this_._internal_uniqueid().empty()) {
      const ::std::string& _s = this_._internal_uniqueid();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "Event.Player.uniqueID");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Event.Player)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t Player::ByteSizeLong(const MessageLite& base) {
  const Player& this_ = static_cast<const Player&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t Player::ByteSizeLong() const {
  const Player& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:Event.Player)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // string uniqueID = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if ((cached_has_bits & 0x00000001U) != 0) {
      if (!this_._internal_uniqueid().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_uniqueid());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void Player::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Player*>(&to_msg);
  auto& from = static_cast<const Player&>(from_msg);
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    from.VerifyHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:Event.Player)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001U) != 0) {
    if (!from._internal_uniqueid().empty()) {
      _this->_internal_set_uniqueid(from._internal_uniqueid());
    } else {
      if (_this->_impl_.uniqueid_.IsDefault()) {
        _this->_internal_set_uniqueid("");
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Player::CopyFrom(const Player& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Event.Player)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Player::InternalSwap(Player* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.uniqueid_, &other->_impl_.uniqueid_, arena);
}

::google::protobuf::Metadata Player::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class JoinRoomRequest::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<JoinRoomRequest>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(JoinRoomRequest, _impl_._has_bits_);
};

JoinRoomRequest::JoinRoomRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, JoinRoomRequest_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Event.JoinRoomRequest)
}
PROTOBUF_NDEBUG_INLINE JoinRoomRequest::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::Event::JoinRoomRequest& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        room_(arena, from.room_) {}

JoinRoomRequest::JoinRoomRequest(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const JoinRoomRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, JoinRoomRequest_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  JoinRoomRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:Event.JoinRoomRequest)
}
PROTOBUF_NDEBUG_INLINE JoinRoomRequest::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        room_(arena) {}

inline void JoinRoomRequest::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
JoinRoomRequest::~JoinRoomRequest() {
  // @@protoc_insertion_point(destructor:Event.JoinRoomRequest)
  SharedDtor(*this);
}
inline void JoinRoomRequest::SharedDtor(MessageLite& self) {
  JoinRoomRequest& this_ = static_cast<JoinRoomRequest&>(self);
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    this_.VerifyHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.room_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL JoinRoomRequest::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) JoinRoomRequest(arena);
}
constexpr auto JoinRoomRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(JoinRoomRequest),
                                            alignof(JoinRoomRequest));
}
constexpr auto JoinRoomRequest::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_JoinRoomRequest_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &JoinRoomRequest::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<JoinRoomRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &JoinRoomRequest::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<JoinRoomRequest>(), &JoinRoomRequest::ByteSizeLong,
              &JoinRoomRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(JoinRoomRequest, _impl_._cached_size_),
          false,
      },
      &JoinRoomRequest::kDescriptorMethods,
      &descriptor_table_event_5fname_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull JoinRoomRequest_class_data_ =
        JoinRoomRequest::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
JoinRoomRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&JoinRoomRequest_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(JoinRoomRequest_class_data_.tc_table);
  return JoinRoomRequest_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 34, 2>
JoinRoomRequest::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(JoinRoomRequest, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    JoinRoomRequest_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Event::JoinRoomRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string room = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(JoinRoomRequest, _impl_.room_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string room = 1;
    {PROTOBUF_FIELD_OFFSET(JoinRoomRequest, _impl_.room_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\25\4\0\0\0\0\0\0"
    "Event.JoinRoomRequest"
    "room"
  }},
};
PROTOBUF_NOINLINE void JoinRoomRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:Event.JoinRoomRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001U) != 0) {
    _impl_.room_.ClearNonDefaultToEmpty();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL JoinRoomRequest::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const JoinRoomRequest& this_ = static_cast<const JoinRoomRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL JoinRoomRequest::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const JoinRoomRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    this_.VerifyHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:Event.JoinRoomRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string room = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000001U) != 0) {
    if (!this_._internal_room().empty()) {
      const ::std::string& _s = this_._internal_room();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "Event.JoinRoomRequest.room");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Event.JoinRoomRequest)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t JoinRoomRequest::ByteSizeLong(const MessageLite& base) {
  const JoinRoomRequest& this_ = static_cast<const JoinRoomRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t JoinRoomRequest::ByteSizeLong() const {
  const JoinRoomRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:Event.JoinRoomRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // string room = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if ((cached_has_bits & 0x00000001U) != 0) {
      if (!this_._internal_room().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_room());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void JoinRoomRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<JoinRoomRequest*>(&to_msg);
  auto& from = static_cast<const JoinRoomRequest&>(from_msg);
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    from.VerifyHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:Event.JoinRoomRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001U) != 0) {
    if (!from._internal_room().empty()) {
      _this->_internal_set_room(from._internal_room());
    } else {
      if (_this->_impl_.room_.IsDefault()) {
        _this->_internal_set_room("");
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void JoinRoomRequest::CopyFrom(const JoinRoomRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Event.JoinRoomRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void JoinRoomRequest::InternalSwap(JoinRoomRequest* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.room_, &other->_impl_.room_, arena);
}

::google::protobuf::Metadata JoinRoomRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class JoinRoomResponse::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<JoinRoomResponse>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(JoinRoomResponse, _impl_._has_bits_);
};

JoinRoomResponse::JoinRoomResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, JoinRoomResponse_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Event.JoinRoomResponse)
}
PROTOBUF_NDEBUG_INLINE JoinRoomResponse::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::Event::JoinRoomResponse& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        player_in_room_{visibility, arena, from.player_in_room_},
        room_(arena, from.room_),
        uniqueid_(arena, from.uniqueid_) {}

JoinRoomResponse::JoinRoomResponse(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const JoinRoomResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, JoinRoomResponse_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  JoinRoomResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:Event.JoinRoomResponse)
}
PROTOBUF_NDEBUG_INLINE JoinRoomResponse::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        player_in_room_{visibility, arena},
        room_(arena),
        uniqueid_(arena) {}

inline void JoinRoomResponse::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
JoinRoomResponse::~JoinRoomResponse() {
  // @@protoc_insertion_point(destructor:Event.JoinRoomResponse)
  SharedDtor(*this);
}
inline void JoinRoomResponse::SharedDtor(MessageLite& self) {
  JoinRoomResponse& this_ = static_cast<JoinRoomResponse&>(self);
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    this_.VerifyHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.room_.Destroy();
  this_._impl_.uniqueid_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL JoinRoomResponse::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) JoinRoomResponse(arena);
}
constexpr auto JoinRoomResponse::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(JoinRoomResponse, _impl_.player_in_room_) +
          decltype(JoinRoomResponse::_impl_.player_in_room_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::CopyInit(
        sizeof(JoinRoomResponse), alignof(JoinRoomResponse), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&JoinRoomResponse::PlacementNew_,
                                 sizeof(JoinRoomResponse),
                                 alignof(JoinRoomResponse));
  }
}
constexpr auto JoinRoomResponse::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_JoinRoomResponse_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &JoinRoomResponse::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<JoinRoomResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &JoinRoomResponse::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<JoinRoomResponse>(), &JoinRoomResponse::ByteSizeLong,
              &JoinRoomResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(JoinRoomResponse, _impl_._cached_size_),
          false,
      },
      &JoinRoomResponse::kDescriptorMethods,
      &descriptor_table_event_5fname_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull JoinRoomResponse_class_data_ =
        JoinRoomResponse::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
JoinRoomResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&JoinRoomResponse_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(JoinRoomResponse_class_data_.tc_table);
  return JoinRoomResponse_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 1, 43, 2>
JoinRoomResponse::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(JoinRoomResponse, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    JoinRoomResponse_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Event::JoinRoomResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string room = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(JoinRoomResponse, _impl_.room_)}},
    // string uniqueID = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 1, 0, PROTOBUF_FIELD_OFFSET(JoinRoomResponse, _impl_.uniqueid_)}},
    // repeated .Event.Player player_in_room = 3;
    {::_pbi::TcParser::FastMtR1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(JoinRoomResponse, _impl_.player_in_room_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string room = 1;
    {PROTOBUF_FIELD_OFFSET(JoinRoomResponse, _impl_.room_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string uniqueID = 2;
    {PROTOBUF_FIELD_OFFSET(JoinRoomResponse, _impl_.uniqueid_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // repeated .Event.Player player_in_room = 3;
    {PROTOBUF_FIELD_OFFSET(JoinRoomResponse, _impl_.player_in_room_), -1, 0, (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::Event::Player>()},
  }},
  {{
    "\26\4\10\0\0\0\0\0"
    "Event.JoinRoomResponse"
    "room"
    "uniqueID"
  }},
};
PROTOBUF_NOINLINE void JoinRoomResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:Event.JoinRoomResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.player_in_room_.Clear();
  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003U) != 0) {
    if ((cached_has_bits & 0x00000001U) != 0) {
      _impl_.room_.ClearNonDefaultToEmpty();
    }
    if ((cached_has_bits & 0x00000002U) != 0) {
      _impl_.uniqueid_.ClearNonDefaultToEmpty();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL JoinRoomResponse::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const JoinRoomResponse& this_ = static_cast<const JoinRoomResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL JoinRoomResponse::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const JoinRoomResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    this_.VerifyHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:Event.JoinRoomResponse)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string room = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000001U) != 0) {
    if (!this_._internal_room().empty()) {
      const ::std::string& _s = this_._internal_room();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "Event.JoinRoomResponse.room");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  // string uniqueID = 2;
  if ((this_._impl_._has_bits_[0] & 0x00000002U) != 0) {
    if (!this_._internal_uniqueid().empty()) {
      const ::std::string& _s = this_._internal_uniqueid();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "Event.JoinRoomResponse.uniqueID");
      target = stream->WriteStringMaybeAliased(2, _s, target);
    }
  }

  // repeated .Event.Player player_in_room = 3;
  for (unsigned i = 0, n = static_cast<unsigned>(
                           this_._internal_player_in_room_size());
       i < n; i++) {
    const auto& repfield = this_._internal_player_in_room().Get(i);
    target =
        ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
            3, repfield, repfield.GetCachedSize(),
            target, stream);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Event.JoinRoomResponse)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t JoinRoomResponse::ByteSizeLong(const MessageLite& base) {
  const JoinRoomResponse& this_ = static_cast<const JoinRoomResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t JoinRoomResponse::ByteSizeLong() const {
  const JoinRoomResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:Event.JoinRoomResponse)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
   {
    // repeated .Event.Player player_in_room = 3;
    {
      total_size += 1UL * this_._internal_player_in_room_size();
      for (const auto& msg : this_._internal_player_in_room()) {
        total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
      }
    }
  }
  cached_has_bits = this_._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003U) != 0) {
    // string room = 1;
    if ((cached_has_bits & 0x00000001U) != 0) {
      if (!this_._internal_room().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_room());
      }
    }
    // string uniqueID = 2;
    if ((cached_has_bits & 0x00000002U) != 0) {
      if (!this_._internal_uniqueid().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_uniqueid());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void JoinRoomResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<JoinRoomResponse*>(&to_msg);
  auto& from = static_cast<const JoinRoomResponse&>(from_msg);
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    from.VerifyHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:Event.JoinRoomResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_player_in_room()->MergeFrom(
      from._internal_player_in_room());
  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003U) != 0) {
    if ((cached_has_bits & 0x00000001U) != 0) {
      if (!from._internal_room().empty()) {
        _this->_internal_set_room(from._internal_room());
      } else {
        if (_this->_impl_.room_.IsDefault()) {
          _this->_internal_set_room("");
        }
      }
    }
    if ((cached_has_bits & 0x00000002U) != 0) {
      if (!from._internal_uniqueid().empty()) {
        _this->_internal_set_uniqueid(from._internal_uniqueid());
      } else {
        if (_this->_impl_.uniqueid_.IsDefault()) {
          _this->_internal_set_uniqueid("");
        }
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void JoinRoomResponse::CopyFrom(const JoinRoomResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Event.JoinRoomResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void JoinRoomResponse::InternalSwap(JoinRoomResponse* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.player_in_room_.InternalSwap(&other->_impl_.player_in_room_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.room_, &other->_impl_.room_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.uniqueid_, &other->_impl_.uniqueid_, arena);
}

::google::protobuf::Metadata JoinRoomResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class RoomStatusRequest::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<RoomStatusRequest>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(RoomStatusRequest, _impl_._has_bits_);
};

RoomStatusRequest::RoomStatusRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, RoomStatusRequest_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Event.RoomStatusRequest)
}
RoomStatusRequest::RoomStatusRequest(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const RoomStatusRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, RoomStatusRequest_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE RoomStatusRequest::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void RoomStatusRequest::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.game_started_ = {};
}
RoomStatusRequest::~RoomStatusRequest() {
  // @@protoc_insertion_point(destructor:Event.RoomStatusRequest)
  SharedDtor(*this);
}
inline void RoomStatusRequest::SharedDtor(MessageLite& self) {
  RoomStatusRequest& this_ = static_cast<RoomStatusRequest&>(self);
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    this_.VerifyHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL RoomStatusRequest::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) RoomStatusRequest(arena);
}
constexpr auto RoomStatusRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(RoomStatusRequest),
                                            alignof(RoomStatusRequest));
}
constexpr auto RoomStatusRequest::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_RoomStatusRequest_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &RoomStatusRequest::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<RoomStatusRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &RoomStatusRequest::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<RoomStatusRequest>(), &RoomStatusRequest::ByteSizeLong,
              &RoomStatusRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(RoomStatusRequest, _impl_._cached_size_),
          false,
      },
      &RoomStatusRequest::kDescriptorMethods,
      &descriptor_table_event_5fname_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull RoomStatusRequest_class_data_ =
        RoomStatusRequest::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
RoomStatusRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&RoomStatusRequest_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(RoomStatusRequest_class_data_.tc_table);
  return RoomStatusRequest_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2>
RoomStatusRequest::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(RoomStatusRequest, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    RoomStatusRequest_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Event::RoomStatusRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // bool game_started = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(RoomStatusRequest, _impl_.game_started_), 0>(),
     {8, 0, 0, PROTOBUF_FIELD_OFFSET(RoomStatusRequest, _impl_.game_started_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bool game_started = 1;
    {PROTOBUF_FIELD_OFFSET(RoomStatusRequest, _impl_.game_started_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kBool)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void RoomStatusRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:Event.RoomStatusRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.game_started_ = false;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL RoomStatusRequest::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const RoomStatusRequest& this_ = static_cast<const RoomStatusRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL RoomStatusRequest::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const RoomStatusRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    this_.VerifyHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:Event.RoomStatusRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // bool game_started = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000001U) != 0) {
    if (this_._internal_game_started() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteBoolToArray(
          1, this_._internal_game_started(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Event.RoomStatusRequest)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t RoomStatusRequest::ByteSizeLong(const MessageLite& base) {
  const RoomStatusRequest& this_ = static_cast<const RoomStatusRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t RoomStatusRequest::ByteSizeLong() const {
  const RoomStatusRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:Event.RoomStatusRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // bool game_started = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if ((cached_has_bits & 0x00000001U) != 0) {
      if (this_._internal_game_started() != 0) {
        total_size += 2;
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void RoomStatusRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<RoomStatusRequest*>(&to_msg);
  auto& from = static_cast<const RoomStatusRequest&>(from_msg);
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    from.VerifyHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:Event.RoomStatusRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001U) != 0) {
    if (from._internal_game_started() != 0) {
      _this->_impl_.game_started_ = from._impl_.game_started_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void RoomStatusRequest::CopyFrom(const RoomStatusRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Event.RoomStatusRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void RoomStatusRequest::InternalSwap(RoomStatusRequest* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.game_started_, other->_impl_.game_started_);
}

::google::protobuf::Metadata RoomStatusRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class Event::_Internal {
 public:
  static constexpr ::int32_t kOneofCaseOffset =
      PROTOBUF_FIELD_OFFSET(::Event::Event, _impl_._oneof_case_);
};

void Event::set_allocated_player_data(::Event::Player* PROTOBUF_NULLABLE player_data) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_Data_Event();
  if (player_data) {
    ::google::protobuf::Arena* submessage_arena = player_data->GetArena();
    if (message_arena != submessage_arena) {
      player_data = ::google::protobuf::internal::GetOwnedMessage(message_arena, player_data, submessage_arena);
    }
    set_has_player_data();
    _impl_.Data_Event_.player_data_ = player_data;
  }
  // @@protoc_insertion_point(field_set_allocated:Event.Event.player_data)
}
void Event::set_allocated_join_room_request(::Event::JoinRoomRequest* PROTOBUF_NULLABLE join_room_request) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_Data_Event();
  if (join_room_request) {
    ::google::protobuf::Arena* submessage_arena = join_room_request->GetArena();
    if (message_arena != submessage_arena) {
      join_room_request = ::google::protobuf::internal::GetOwnedMessage(message_arena, join_room_request, submessage_arena);
    }
    set_has_join_room_request();
    _impl_.Data_Event_.join_room_request_ = join_room_request;
  }
  // @@protoc_insertion_point(field_set_allocated:Event.Event.join_room_request)
}
void Event::set_allocated_join_room_response(::Event::JoinRoomResponse* PROTOBUF_NULLABLE join_room_response) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_Data_Event();
  if (join_room_response) {
    ::google::protobuf::Arena* submessage_arena = join_room_response->GetArena();
    if (message_arena != submessage_arena) {
      join_room_response = ::google::protobuf::internal::GetOwnedMessage(message_arena, join_room_response, submessage_arena);
    }
    set_has_join_room_response();
    _impl_.Data_Event_.join_room_response_ = join_room_response;
  }
  // @@protoc_insertion_point(field_set_allocated:Event.Event.join_room_response)
}
void Event::set_allocated_room_status_request(::Event::RoomStatusRequest* PROTOBUF_NULLABLE room_status_request) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_Data_Event();
  if (room_status_request) {
    ::google::protobuf::Arena* submessage_arena = room_status_request->GetArena();
    if (message_arena != submessage_arena) {
      room_status_request = ::google::protobuf::internal::GetOwnedMessage(message_arena, room_status_request, submessage_arena);
    }
    set_has_room_status_request();
    _impl_.Data_Event_.room_status_request_ = room_status_request;
  }
  // @@protoc_insertion_point(field_set_allocated:Event.Event.room_status_request)
}
Event::Event(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Event_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Event.Event)
}
PROTOBUF_NDEBUG_INLINE Event::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::Event::Event& from_msg)
      : Data_Event_{},
        _cached_size_{0},
        _oneof_case_{from._oneof_case_[0]} {}

Event::Event(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const Event& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Event_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Event* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  switch (Data_Event_case()) {
    case DATA_EVENT_NOT_SET:
      break;
      case kPlayerData:
        _impl_.Data_Event_.player_data_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.Data_Event_.player_data_);
        break;
      case kJoinRoomRequest:
        _impl_.Data_Event_.join_room_request_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.Data_Event_.join_room_request_);
        break;
      case kJoinRoomResponse:
        _impl_.Data_Event_.join_room_response_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.Data_Event_.join_room_response_);
        break;
      case kRoomStatusRequest:
        _impl_.Data_Event_.room_status_request_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.Data_Event_.room_status_request_);
        break;
  }

  // @@protoc_insertion_point(copy_constructor:Event.Event)
}
PROTOBUF_NDEBUG_INLINE Event::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : Data_Event_{},
        _cached_size_{0},
        _oneof_case_{} {}

inline void Event::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
Event::~Event() {
  // @@protoc_insertion_point(destructor:Event.Event)
  SharedDtor(*this);
}
inline void Event::SharedDtor(MessageLite& self) {
  Event& this_ = static_cast<Event&>(self);
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    this_.VerifyHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  if (this_.has_Data_Event()) {
    this_.clear_Data_Event();
  }
  this_._impl_.~Impl_();
}

void Event::clear_Data_Event() {
// @@protoc_insertion_point(one_of_clear_start:Event.Event)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  switch (Data_Event_case()) {
    case kPlayerData: {
      if (GetArena() == nullptr) {
        delete _impl_.Data_Event_.player_data_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.Data_Event_.player_data_);
      }
      break;
    }
    case kJoinRoomRequest: {
      if (GetArena() == nullptr) {
        delete _impl_.Data_Event_.join_room_request_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.Data_Event_.join_room_request_);
      }
      break;
    }
    case kJoinRoomResponse: {
      if (GetArena() == nullptr) {
        delete _impl_.Data_Event_.join_room_response_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.Data_Event_.join_room_response_);
      }
      break;
    }
    case kRoomStatusRequest: {
      if (GetArena() == nullptr) {
        delete _impl_.Data_Event_.room_status_request_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.Data_Event_.room_status_request_);
      }
      break;
    }
    case DATA_EVENT_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = DATA_EVENT_NOT_SET;
}


inline void* PROTOBUF_NONNULL Event::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) Event(arena);
}
constexpr auto Event::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(Event),
                                            alignof(Event));
}
constexpr auto Event::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_Event_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &Event::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<Event>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &Event::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<Event>(), &Event::ByteSizeLong,
              &Event::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(Event, _impl_._cached_size_),
          false,
      },
      &Event::kDescriptorMethods,
      &descriptor_table_event_5fname_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull Event_class_data_ =
        Event::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
Event::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&Event_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(Event_class_data_.tc_table);
  return Event_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 4, 4, 0, 2>
Event::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    4, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    4,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    Event_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Event::Event>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // .Event.Player player_data = 1;
    {PROTOBUF_FIELD_OFFSET(Event, _impl_.Data_Event_.player_data_), _Internal::kOneofCaseOffset + 0, 0, (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .Event.JoinRoomRequest join_room_request = 2;
    {PROTOBUF_FIELD_OFFSET(Event, _impl_.Data_Event_.join_room_request_), _Internal::kOneofCaseOffset + 0, 1, (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .Event.JoinRoomResponse join_room_response = 3;
    {PROTOBUF_FIELD_OFFSET(Event, _impl_.Data_Event_.join_room_response_), _Internal::kOneofCaseOffset + 0, 2, (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .Event.RoomStatusRequest room_status_request = 4;
    {PROTOBUF_FIELD_OFFSET(Event, _impl_.Data_Event_.room_status_request_), _Internal::kOneofCaseOffset + 0, 3, (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::Event::Player>()},
      {::_pbi::TcParser::GetTable<::Event::JoinRoomRequest>()},
      {::_pbi::TcParser::GetTable<::Event::JoinRoomResponse>()},
      {::_pbi::TcParser::GetTable<::Event::RoomStatusRequest>()},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void Event::Clear() {
// @@protoc_insertion_point(message_clear_start:Event.Event)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  clear_Data_Event();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL Event::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const Event& this_ = static_cast<const Event&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL Event::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const Event& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    this_.VerifyHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:Event.Event)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  switch (this_.Data_Event_case()) {
    case kPlayerData: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          1, *this_._impl_.Data_Event_.player_data_, this_._impl_.Data_Event_.player_data_->GetCachedSize(), target,
          stream);
      break;
    }
    case kJoinRoomRequest: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          2, *this_._impl_.Data_Event_.join_room_request_, this_._impl_.Data_Event_.join_room_request_->GetCachedSize(), target,
          stream);
      break;
    }
    case kJoinRoomResponse: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          3, *this_._impl_.Data_Event_.join_room_response_, this_._impl_.Data_Event_.join_room_response_->GetCachedSize(), target,
          stream);
      break;
    }
    case kRoomStatusRequest: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          4, *this_._impl_.Data_Event_.room_status_request_, this_._impl_.Data_Event_.room_status_request_->GetCachedSize(), target,
          stream);
      break;
    }
    default:
      break;
  }
  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Event.Event)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t Event::ByteSizeLong(const MessageLite& base) {
  const Event& this_ = static_cast<const Event&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t Event::ByteSizeLong() const {
  const Event& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:Event.Event)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  switch (this_.Data_Event_case()) {
    // .Event.Player player_data = 1;
    case kPlayerData: {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.Data_Event_.player_data_);
      break;
    }
    // .Event.JoinRoomRequest join_room_request = 2;
    case kJoinRoomRequest: {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.Data_Event_.join_room_request_);
      break;
    }
    // .Event.JoinRoomResponse join_room_response = 3;
    case kJoinRoomResponse: {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.Data_Event_.join_room_response_);
      break;
    }
    // .Event.RoomStatusRequest room_status_request = 4;
    case kRoomStatusRequest: {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.Data_Event_.room_status_request_);
      break;
    }
    case DATA_EVENT_NOT_SET: {
      break;
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void Event::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Event*>(&to_msg);
  auto& from = static_cast<const Event&>(from_msg);
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    from.VerifyHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:Event.Event)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (const uint32_t oneof_from_case = from._impl_._oneof_case_[0]) {
    const uint32_t oneof_to_case = _this->_impl_._oneof_case_[0];
    const bool oneof_needs_init = oneof_to_case != oneof_from_case;
    if (oneof_needs_init) {
      if (oneof_to_case != 0) {
        _this->clear_Data_Event();
      }
      _this->_impl_._oneof_case_[0] = oneof_from_case;
    }

    switch (oneof_from_case) {
      case kPlayerData: {
        if (oneof_needs_init) {
          _this->_impl_.Data_Event_.player_data_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.Data_Event_.player_data_);
        } else {
          _this->_impl_.Data_Event_.player_data_->MergeFrom(*from._impl_.Data_Event_.player_data_);
        }
        break;
      }
      case kJoinRoomRequest: {
        if (oneof_needs_init) {
          _this->_impl_.Data_Event_.join_room_request_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.Data_Event_.join_room_request_);
        } else {
          _this->_impl_.Data_Event_.join_room_request_->MergeFrom(*from._impl_.Data_Event_.join_room_request_);
        }
        break;
      }
      case kJoinRoomResponse: {
        if (oneof_needs_init) {
          _this->_impl_.Data_Event_.join_room_response_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.Data_Event_.join_room_response_);
        } else {
          _this->_impl_.Data_Event_.join_room_response_->MergeFrom(*from._impl_.Data_Event_.join_room_response_);
        }
        break;
      }
      case kRoomStatusRequest: {
        if (oneof_needs_init) {
          _this->_impl_.Data_Event_.room_status_request_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.Data_Event_.room_status_request_);
        } else {
          _this->_impl_.Data_Event_.room_status_request_->MergeFrom(*from._impl_.Data_Event_.room_status_request_);
        }
        break;
      }
      case DATA_EVENT_NOT_SET:
        break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Event::CopyFrom(const Event& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Event.Event)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Event::InternalSwap(Event* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.Data_Event_, other->_impl_.Data_Event_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::google::protobuf::Metadata Event::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace Event
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_event_5fname_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
