// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: event_name.proto
// Protobuf C++ Version: 6.32.0

#ifndef event_5fname_2eproto_2epb_2eh
#define event_5fname_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6032000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_event_5fname_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_event_5fname_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_event_5fname_2eproto;
}  // extern "C"
namespace Event {
class Event;
struct EventDefaultTypeInternal;
extern EventDefaultTypeInternal _Event_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull Event_class_data_;
class JoinRoomRequest;
struct JoinRoomRequestDefaultTypeInternal;
extern JoinRoomRequestDefaultTypeInternal _JoinRoomRequest_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull JoinRoomRequest_class_data_;
class JoinRoomResponse;
struct JoinRoomResponseDefaultTypeInternal;
extern JoinRoomResponseDefaultTypeInternal _JoinRoomResponse_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull JoinRoomResponse_class_data_;
class Player;
struct PlayerDefaultTypeInternal;
extern PlayerDefaultTypeInternal _Player_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull Player_class_data_;
class RoomStatusRequest;
struct RoomStatusRequestDefaultTypeInternal;
extern RoomStatusRequestDefaultTypeInternal _RoomStatusRequest_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull RoomStatusRequest_class_data_;
}  // namespace Event
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace Event {

// ===================================================================


// -------------------------------------------------------------------

class RoomStatusRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Event.RoomStatusRequest) */ {
 public:
  inline RoomStatusRequest() : RoomStatusRequest(nullptr) {}
  ~RoomStatusRequest() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(RoomStatusRequest* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(RoomStatusRequest));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR RoomStatusRequest(::google::protobuf::internal::ConstantInitialized);

  inline RoomStatusRequest(const RoomStatusRequest& from) : RoomStatusRequest(nullptr, from) {}
  inline RoomStatusRequest(RoomStatusRequest&& from) noexcept
      : RoomStatusRequest(nullptr, ::std::move(from)) {}
  inline RoomStatusRequest& operator=(const RoomStatusRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline RoomStatusRequest& operator=(RoomStatusRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RoomStatusRequest& default_instance() {
    return *reinterpret_cast<const RoomStatusRequest*>(
        &_RoomStatusRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(RoomStatusRequest& a, RoomStatusRequest& b) { a.Swap(&b); }
  inline void Swap(RoomStatusRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RoomStatusRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RoomStatusRequest* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<RoomStatusRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const RoomStatusRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const RoomStatusRequest& from) { RoomStatusRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(RoomStatusRequest* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Event.RoomStatusRequest"; }

 protected:
  explicit RoomStatusRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  RoomStatusRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const RoomStatusRequest& from);
  RoomStatusRequest(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, RoomStatusRequest&& from) noexcept
      : RoomStatusRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kGameStartedFieldNumber = 1,
  };
  // bool game_started = 1;
  void clear_game_started() ;
  bool game_started() const;
  void set_game_started(bool value);

  private:
  bool _internal_game_started() const;
  void _internal_set_game_started(bool value);

  public:
  // @@protoc_insertion_point(class_scope:Event.RoomStatusRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const RoomStatusRequest& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    bool game_started_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_event_5fname_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull RoomStatusRequest_class_data_;
// -------------------------------------------------------------------

class Player final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Event.Player) */ {
 public:
  inline Player() : Player(nullptr) {}
  ~Player() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Player* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Player));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Player(::google::protobuf::internal::ConstantInitialized);

  inline Player(const Player& from) : Player(nullptr, from) {}
  inline Player(Player&& from) noexcept
      : Player(nullptr, ::std::move(from)) {}
  inline Player& operator=(const Player& from) {
    CopyFrom(from);
    return *this;
  }
  inline Player& operator=(Player&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Player& default_instance() {
    return *reinterpret_cast<const Player*>(
        &_Player_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(Player& a, Player& b) { a.Swap(&b); }
  inline void Swap(Player* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Player* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Player* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Player>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Player& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Player& from) { Player::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Player* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Event.Player"; }

 protected:
  explicit Player(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  Player(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Player& from);
  Player(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, Player&& from) noexcept
      : Player(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kUniqueIDFieldNumber = 1,
  };
  // string uniqueID = 1;
  void clear_uniqueid() ;
  const ::std::string& uniqueid() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_uniqueid(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_uniqueid();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_uniqueid();
  void set_allocated_uniqueid(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_uniqueid() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_uniqueid(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_uniqueid();

  public:
  // @@protoc_insertion_point(class_scope:Event.Player)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 29,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const Player& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr uniqueid_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_event_5fname_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull Player_class_data_;
// -------------------------------------------------------------------

class JoinRoomRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Event.JoinRoomRequest) */ {
 public:
  inline JoinRoomRequest() : JoinRoomRequest(nullptr) {}
  ~JoinRoomRequest() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(JoinRoomRequest* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(JoinRoomRequest));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR JoinRoomRequest(::google::protobuf::internal::ConstantInitialized);

  inline JoinRoomRequest(const JoinRoomRequest& from) : JoinRoomRequest(nullptr, from) {}
  inline JoinRoomRequest(JoinRoomRequest&& from) noexcept
      : JoinRoomRequest(nullptr, ::std::move(from)) {}
  inline JoinRoomRequest& operator=(const JoinRoomRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline JoinRoomRequest& operator=(JoinRoomRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const JoinRoomRequest& default_instance() {
    return *reinterpret_cast<const JoinRoomRequest*>(
        &_JoinRoomRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(JoinRoomRequest& a, JoinRoomRequest& b) { a.Swap(&b); }
  inline void Swap(JoinRoomRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(JoinRoomRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  JoinRoomRequest* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<JoinRoomRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const JoinRoomRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const JoinRoomRequest& from) { JoinRoomRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(JoinRoomRequest* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Event.JoinRoomRequest"; }

 protected:
  explicit JoinRoomRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  JoinRoomRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const JoinRoomRequest& from);
  JoinRoomRequest(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, JoinRoomRequest&& from) noexcept
      : JoinRoomRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kRoomFieldNumber = 1,
  };
  // string room = 1;
  void clear_room() ;
  const ::std::string& room() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_room(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_room();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_room();
  void set_allocated_room(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_room() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_room(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_room();

  public:
  // @@protoc_insertion_point(class_scope:Event.JoinRoomRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 34,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const JoinRoomRequest& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr room_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_event_5fname_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull JoinRoomRequest_class_data_;
// -------------------------------------------------------------------

class JoinRoomResponse final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Event.JoinRoomResponse) */ {
 public:
  inline JoinRoomResponse() : JoinRoomResponse(nullptr) {}
  ~JoinRoomResponse() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(JoinRoomResponse* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(JoinRoomResponse));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR JoinRoomResponse(::google::protobuf::internal::ConstantInitialized);

  inline JoinRoomResponse(const JoinRoomResponse& from) : JoinRoomResponse(nullptr, from) {}
  inline JoinRoomResponse(JoinRoomResponse&& from) noexcept
      : JoinRoomResponse(nullptr, ::std::move(from)) {}
  inline JoinRoomResponse& operator=(const JoinRoomResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline JoinRoomResponse& operator=(JoinRoomResponse&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const JoinRoomResponse& default_instance() {
    return *reinterpret_cast<const JoinRoomResponse*>(
        &_JoinRoomResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(JoinRoomResponse& a, JoinRoomResponse& b) { a.Swap(&b); }
  inline void Swap(JoinRoomResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(JoinRoomResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  JoinRoomResponse* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<JoinRoomResponse>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const JoinRoomResponse& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const JoinRoomResponse& from) { JoinRoomResponse::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(JoinRoomResponse* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Event.JoinRoomResponse"; }

 protected:
  explicit JoinRoomResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  JoinRoomResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const JoinRoomResponse& from);
  JoinRoomResponse(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, JoinRoomResponse&& from) noexcept
      : JoinRoomResponse(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kPlayerInRoomFieldNumber = 3,
    kRoomFieldNumber = 1,
    kUniqueIDFieldNumber = 2,
  };
  // repeated .Event.Player player_in_room = 3;
  int player_in_room_size() const;
  private:
  int _internal_player_in_room_size() const;

  public:
  void clear_player_in_room() ;
  ::Event::Player* PROTOBUF_NONNULL mutable_player_in_room(int index);
  ::google::protobuf::RepeatedPtrField<::Event::Player>* PROTOBUF_NONNULL mutable_player_in_room();

  private:
  const ::google::protobuf::RepeatedPtrField<::Event::Player>& _internal_player_in_room() const;
  ::google::protobuf::RepeatedPtrField<::Event::Player>* PROTOBUF_NONNULL _internal_mutable_player_in_room();
  public:
  const ::Event::Player& player_in_room(int index) const;
  ::Event::Player* PROTOBUF_NONNULL add_player_in_room();
  const ::google::protobuf::RepeatedPtrField<::Event::Player>& player_in_room() const;
  // string room = 1;
  void clear_room() ;
  const ::std::string& room() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_room(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_room();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_room();
  void set_allocated_room(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_room() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_room(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_room();

  public:
  // string uniqueID = 2;
  void clear_uniqueid() ;
  const ::std::string& uniqueid() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_uniqueid(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_uniqueid();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_uniqueid();
  void set_allocated_uniqueid(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_uniqueid() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_uniqueid(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_uniqueid();

  public:
  // @@protoc_insertion_point(class_scope:Event.JoinRoomResponse)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 3,
                                   1, 43,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const JoinRoomResponse& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField< ::Event::Player > player_in_room_;
    ::google::protobuf::internal::ArenaStringPtr room_;
    ::google::protobuf::internal::ArenaStringPtr uniqueid_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_event_5fname_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull JoinRoomResponse_class_data_;
// -------------------------------------------------------------------

class Event final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Event.Event) */ {
 public:
  inline Event() : Event(nullptr) {}
  ~Event() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Event* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Event));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Event(::google::protobuf::internal::ConstantInitialized);

  inline Event(const Event& from) : Event(nullptr, from) {}
  inline Event(Event&& from) noexcept
      : Event(nullptr, ::std::move(from)) {}
  inline Event& operator=(const Event& from) {
    CopyFrom(from);
    return *this;
  }
  inline Event& operator=(Event&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Event& default_instance() {
    return *reinterpret_cast<const Event*>(
        &_Event_default_instance_);
  }
  enum DataEventCase {
    kPlayerData = 1,
    kJoinRoomRequest = 2,
    kJoinRoomResponse = 3,
    kRoomStatusRequest = 4,
    DATA_EVENT_NOT_SET = 0,
  };
  static constexpr int kIndexInFileMessages = 4;
  friend void swap(Event& a, Event& b) { a.Swap(&b); }
  inline void Swap(Event* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Event* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Event* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Event>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Event& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Event& from) { Event::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Event* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Event.Event"; }

 protected:
  explicit Event(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  Event(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Event& from);
  Event(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, Event&& from) noexcept
      : Event(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kPlayerDataFieldNumber = 1,
    kJoinRoomRequestFieldNumber = 2,
    kJoinRoomResponseFieldNumber = 3,
    kRoomStatusRequestFieldNumber = 4,
  };
  // .Event.Player player_data = 1;
  bool has_player_data() const;
  private:
  bool _internal_has_player_data() const;

  public:
  void clear_player_data() ;
  const ::Event::Player& player_data() const;
  [[nodiscard]] ::Event::Player* PROTOBUF_NULLABLE release_player_data();
  ::Event::Player* PROTOBUF_NONNULL mutable_player_data();
  void set_allocated_player_data(::Event::Player* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_player_data(::Event::Player* PROTOBUF_NULLABLE value);
  ::Event::Player* PROTOBUF_NULLABLE unsafe_arena_release_player_data();

  private:
  const ::Event::Player& _internal_player_data() const;
  ::Event::Player* PROTOBUF_NONNULL _internal_mutable_player_data();

  public:
  // .Event.JoinRoomRequest join_room_request = 2;
  bool has_join_room_request() const;
  private:
  bool _internal_has_join_room_request() const;

  public:
  void clear_join_room_request() ;
  const ::Event::JoinRoomRequest& join_room_request() const;
  [[nodiscard]] ::Event::JoinRoomRequest* PROTOBUF_NULLABLE release_join_room_request();
  ::Event::JoinRoomRequest* PROTOBUF_NONNULL mutable_join_room_request();
  void set_allocated_join_room_request(::Event::JoinRoomRequest* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_join_room_request(::Event::JoinRoomRequest* PROTOBUF_NULLABLE value);
  ::Event::JoinRoomRequest* PROTOBUF_NULLABLE unsafe_arena_release_join_room_request();

  private:
  const ::Event::JoinRoomRequest& _internal_join_room_request() const;
  ::Event::JoinRoomRequest* PROTOBUF_NONNULL _internal_mutable_join_room_request();

  public:
  // .Event.JoinRoomResponse join_room_response = 3;
  bool has_join_room_response() const;
  private:
  bool _internal_has_join_room_response() const;

  public:
  void clear_join_room_response() ;
  const ::Event::JoinRoomResponse& join_room_response() const;
  [[nodiscard]] ::Event::JoinRoomResponse* PROTOBUF_NULLABLE release_join_room_response();
  ::Event::JoinRoomResponse* PROTOBUF_NONNULL mutable_join_room_response();
  void set_allocated_join_room_response(::Event::JoinRoomResponse* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_join_room_response(::Event::JoinRoomResponse* PROTOBUF_NULLABLE value);
  ::Event::JoinRoomResponse* PROTOBUF_NULLABLE unsafe_arena_release_join_room_response();

  private:
  const ::Event::JoinRoomResponse& _internal_join_room_response() const;
  ::Event::JoinRoomResponse* PROTOBUF_NONNULL _internal_mutable_join_room_response();

  public:
  // .Event.RoomStatusRequest room_status_request = 4;
  bool has_room_status_request() const;
  private:
  bool _internal_has_room_status_request() const;

  public:
  void clear_room_status_request() ;
  const ::Event::RoomStatusRequest& room_status_request() const;
  [[nodiscard]] ::Event::RoomStatusRequest* PROTOBUF_NULLABLE release_room_status_request();
  ::Event::RoomStatusRequest* PROTOBUF_NONNULL mutable_room_status_request();
  void set_allocated_room_status_request(::Event::RoomStatusRequest* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_room_status_request(::Event::RoomStatusRequest* PROTOBUF_NULLABLE value);
  ::Event::RoomStatusRequest* PROTOBUF_NULLABLE unsafe_arena_release_room_status_request();

  private:
  const ::Event::RoomStatusRequest& _internal_room_status_request() const;
  ::Event::RoomStatusRequest* PROTOBUF_NONNULL _internal_mutable_room_status_request();

  public:
  void clear_Data_Event();
  DataEventCase Data_Event_case() const;
  // @@protoc_insertion_point(class_scope:Event.Event)
 private:
  class _Internal;
  void set_has_player_data();
  void set_has_join_room_request();
  void set_has_join_room_response();
  void set_has_room_status_request();
  inline bool has_Data_Event() const;
  inline void clear_has_Data_Event();
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 4,
                                   4, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const Event& from_msg);
    union DataEventUnion {
      constexpr DataEventUnion() : _constinit_{} {}
      ::google::protobuf::internal::ConstantInitialized _constinit_;
      ::google::protobuf::Message* PROTOBUF_NULLABLE player_data_;
      ::google::protobuf::Message* PROTOBUF_NULLABLE join_room_request_;
      ::google::protobuf::Message* PROTOBUF_NULLABLE join_room_response_;
      ::google::protobuf::Message* PROTOBUF_NULLABLE room_status_request_;
    } Data_Event_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::uint32_t _oneof_case_[1];
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_event_5fname_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull Event_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// Player

// string uniqueID = 1;
inline void Player::clear_uniqueid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.uniqueid_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001U;
}
inline const ::std::string& Player::uniqueid() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Event.Player.uniqueID)
  return _internal_uniqueid();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void Player::set_uniqueid(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001U;
  _impl_.uniqueid_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Event.Player.uniqueID)
}
inline ::std::string* PROTOBUF_NONNULL Player::mutable_uniqueid()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_uniqueid();
  // @@protoc_insertion_point(field_mutable:Event.Player.uniqueID)
  return _s;
}
inline const ::std::string& Player::_internal_uniqueid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.uniqueid_.Get();
}
inline void Player::_internal_set_uniqueid(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001U;
  _impl_.uniqueid_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL Player::_internal_mutable_uniqueid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001U;
  return _impl_.uniqueid_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE Player::release_uniqueid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Event.Player.uniqueID)
  if ((_impl_._has_bits_[0] & 0x00000001U) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001U;
  auto* released = _impl_.uniqueid_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.uniqueid_.Set("", GetArena());
  }
  return released;
}
inline void Player::set_allocated_uniqueid(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001U;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001U;
  }
  _impl_.uniqueid_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.uniqueid_.IsDefault()) {
    _impl_.uniqueid_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:Event.Player.uniqueID)
}

// -------------------------------------------------------------------

// JoinRoomRequest

// string room = 1;
inline void JoinRoomRequest::clear_room() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.room_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001U;
}
inline const ::std::string& JoinRoomRequest::room() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Event.JoinRoomRequest.room)
  return _internal_room();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void JoinRoomRequest::set_room(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001U;
  _impl_.room_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Event.JoinRoomRequest.room)
}
inline ::std::string* PROTOBUF_NONNULL JoinRoomRequest::mutable_room()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_room();
  // @@protoc_insertion_point(field_mutable:Event.JoinRoomRequest.room)
  return _s;
}
inline const ::std::string& JoinRoomRequest::_internal_room() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.room_.Get();
}
inline void JoinRoomRequest::_internal_set_room(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001U;
  _impl_.room_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL JoinRoomRequest::_internal_mutable_room() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001U;
  return _impl_.room_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE JoinRoomRequest::release_room() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Event.JoinRoomRequest.room)
  if ((_impl_._has_bits_[0] & 0x00000001U) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001U;
  auto* released = _impl_.room_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.room_.Set("", GetArena());
  }
  return released;
}
inline void JoinRoomRequest::set_allocated_room(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001U;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001U;
  }
  _impl_.room_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.room_.IsDefault()) {
    _impl_.room_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:Event.JoinRoomRequest.room)
}

// -------------------------------------------------------------------

// JoinRoomResponse

// string room = 1;
inline void JoinRoomResponse::clear_room() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.room_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001U;
}
inline const ::std::string& JoinRoomResponse::room() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Event.JoinRoomResponse.room)
  return _internal_room();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void JoinRoomResponse::set_room(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001U;
  _impl_.room_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Event.JoinRoomResponse.room)
}
inline ::std::string* PROTOBUF_NONNULL JoinRoomResponse::mutable_room()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_room();
  // @@protoc_insertion_point(field_mutable:Event.JoinRoomResponse.room)
  return _s;
}
inline const ::std::string& JoinRoomResponse::_internal_room() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.room_.Get();
}
inline void JoinRoomResponse::_internal_set_room(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001U;
  _impl_.room_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL JoinRoomResponse::_internal_mutable_room() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001U;
  return _impl_.room_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE JoinRoomResponse::release_room() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Event.JoinRoomResponse.room)
  if ((_impl_._has_bits_[0] & 0x00000001U) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001U;
  auto* released = _impl_.room_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.room_.Set("", GetArena());
  }
  return released;
}
inline void JoinRoomResponse::set_allocated_room(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001U;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001U;
  }
  _impl_.room_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.room_.IsDefault()) {
    _impl_.room_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:Event.JoinRoomResponse.room)
}

// string uniqueID = 2;
inline void JoinRoomResponse::clear_uniqueid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.uniqueid_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000002U;
}
inline const ::std::string& JoinRoomResponse::uniqueid() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Event.JoinRoomResponse.uniqueID)
  return _internal_uniqueid();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void JoinRoomResponse::set_uniqueid(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002U;
  _impl_.uniqueid_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Event.JoinRoomResponse.uniqueID)
}
inline ::std::string* PROTOBUF_NONNULL JoinRoomResponse::mutable_uniqueid()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_uniqueid();
  // @@protoc_insertion_point(field_mutable:Event.JoinRoomResponse.uniqueID)
  return _s;
}
inline const ::std::string& JoinRoomResponse::_internal_uniqueid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.uniqueid_.Get();
}
inline void JoinRoomResponse::_internal_set_uniqueid(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002U;
  _impl_.uniqueid_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL JoinRoomResponse::_internal_mutable_uniqueid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002U;
  return _impl_.uniqueid_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE JoinRoomResponse::release_uniqueid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Event.JoinRoomResponse.uniqueID)
  if ((_impl_._has_bits_[0] & 0x00000002U) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000002U;
  auto* released = _impl_.uniqueid_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.uniqueid_.Set("", GetArena());
  }
  return released;
}
inline void JoinRoomResponse::set_allocated_uniqueid(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002U;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002U;
  }
  _impl_.uniqueid_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.uniqueid_.IsDefault()) {
    _impl_.uniqueid_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:Event.JoinRoomResponse.uniqueID)
}

// repeated .Event.Player player_in_room = 3;
inline int JoinRoomResponse::_internal_player_in_room_size() const {
  return _internal_player_in_room().size();
}
inline int JoinRoomResponse::player_in_room_size() const {
  return _internal_player_in_room_size();
}
inline void JoinRoomResponse::clear_player_in_room() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.player_in_room_.Clear();
}
inline ::Event::Player* PROTOBUF_NONNULL JoinRoomResponse::mutable_player_in_room(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:Event.JoinRoomResponse.player_in_room)
  return _internal_mutable_player_in_room()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::Event::Player>* PROTOBUF_NONNULL JoinRoomResponse::mutable_player_in_room()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:Event.JoinRoomResponse.player_in_room)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_player_in_room();
}
inline const ::Event::Player& JoinRoomResponse::player_in_room(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Event.JoinRoomResponse.player_in_room)
  return _internal_player_in_room().Get(index);
}
inline ::Event::Player* PROTOBUF_NONNULL JoinRoomResponse::add_player_in_room()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::Event::Player* _add = _internal_mutable_player_in_room()->Add();
  // @@protoc_insertion_point(field_add:Event.JoinRoomResponse.player_in_room)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::Event::Player>& JoinRoomResponse::player_in_room() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:Event.JoinRoomResponse.player_in_room)
  return _internal_player_in_room();
}
inline const ::google::protobuf::RepeatedPtrField<::Event::Player>&
JoinRoomResponse::_internal_player_in_room() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.player_in_room_;
}
inline ::google::protobuf::RepeatedPtrField<::Event::Player>* PROTOBUF_NONNULL
JoinRoomResponse::_internal_mutable_player_in_room() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.player_in_room_;
}

// -------------------------------------------------------------------

// RoomStatusRequest

// bool game_started = 1;
inline void RoomStatusRequest::clear_game_started() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.game_started_ = false;
  _impl_._has_bits_[0] &= ~0x00000001U;
}
inline bool RoomStatusRequest::game_started() const {
  // @@protoc_insertion_point(field_get:Event.RoomStatusRequest.game_started)
  return _internal_game_started();
}
inline void RoomStatusRequest::set_game_started(bool value) {
  _internal_set_game_started(value);
  _impl_._has_bits_[0] |= 0x00000001U;
  // @@protoc_insertion_point(field_set:Event.RoomStatusRequest.game_started)
}
inline bool RoomStatusRequest::_internal_game_started() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.game_started_;
}
inline void RoomStatusRequest::_internal_set_game_started(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.game_started_ = value;
}

// -------------------------------------------------------------------

// Event

// .Event.Player player_data = 1;
inline bool Event::has_player_data() const {
  return Data_Event_case() == kPlayerData;
}
inline bool Event::_internal_has_player_data() const {
  return Data_Event_case() == kPlayerData;
}
inline void Event::set_has_player_data() {
  _impl_._oneof_case_[0] = kPlayerData;
}
inline void Event::clear_player_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (Data_Event_case() == kPlayerData) {
    if (GetArena() == nullptr) {
      delete _impl_.Data_Event_.player_data_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.Data_Event_.player_data_);
    }
    clear_has_Data_Event();
  }
}
inline ::Event::Player* PROTOBUF_NULLABLE Event::release_player_data() {
  // @@protoc_insertion_point(field_release:Event.Event.player_data)
  if (Data_Event_case() == kPlayerData) {
    clear_has_Data_Event();
    auto* temp = reinterpret_cast<::Event::Player*>(_impl_.Data_Event_.player_data_);
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.Data_Event_.player_data_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::Event::Player& Event::_internal_player_data() const {
  return Data_Event_case() == kPlayerData ? *reinterpret_cast<::Event::Player*>(_impl_.Data_Event_.player_data_) : reinterpret_cast<::Event::Player&>(::Event::_Player_default_instance_);
}
inline const ::Event::Player& Event::player_data() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Event.Event.player_data)
  return _internal_player_data();
}
inline ::Event::Player* PROTOBUF_NULLABLE Event::unsafe_arena_release_player_data() {
  // @@protoc_insertion_point(field_unsafe_arena_release:Event.Event.player_data)
  if (Data_Event_case() == kPlayerData) {
    clear_has_Data_Event();
    auto* temp = reinterpret_cast<::Event::Player*>(_impl_.Data_Event_.player_data_);
    _impl_.Data_Event_.player_data_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void Event::unsafe_arena_set_allocated_player_data(
    ::Event::Player* PROTOBUF_NULLABLE value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_Data_Event();
  if (value) {
    set_has_player_data();
    _impl_.Data_Event_.player_data_ = reinterpret_cast<::google::protobuf::Message*>(value);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Event.Event.player_data)
}
inline ::Event::Player* PROTOBUF_NONNULL Event::_internal_mutable_player_data() {
  if (Data_Event_case() != kPlayerData) {
    clear_Data_Event();
    set_has_player_data();
    _impl_.Data_Event_.player_data_ = reinterpret_cast<::google::protobuf::Message*>(
        ::google::protobuf::Message::DefaultConstruct<::Event::Player>(GetArena()));
  }
  return reinterpret_cast<::Event::Player*>(_impl_.Data_Event_.player_data_);
}
inline ::Event::Player* PROTOBUF_NONNULL Event::mutable_player_data()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::Event::Player* _msg = _internal_mutable_player_data();
  // @@protoc_insertion_point(field_mutable:Event.Event.player_data)
  return _msg;
}

// .Event.JoinRoomRequest join_room_request = 2;
inline bool Event::has_join_room_request() const {
  return Data_Event_case() == kJoinRoomRequest;
}
inline bool Event::_internal_has_join_room_request() const {
  return Data_Event_case() == kJoinRoomRequest;
}
inline void Event::set_has_join_room_request() {
  _impl_._oneof_case_[0] = kJoinRoomRequest;
}
inline void Event::clear_join_room_request() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (Data_Event_case() == kJoinRoomRequest) {
    if (GetArena() == nullptr) {
      delete _impl_.Data_Event_.join_room_request_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.Data_Event_.join_room_request_);
    }
    clear_has_Data_Event();
  }
}
inline ::Event::JoinRoomRequest* PROTOBUF_NULLABLE Event::release_join_room_request() {
  // @@protoc_insertion_point(field_release:Event.Event.join_room_request)
  if (Data_Event_case() == kJoinRoomRequest) {
    clear_has_Data_Event();
    auto* temp = reinterpret_cast<::Event::JoinRoomRequest*>(_impl_.Data_Event_.join_room_request_);
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.Data_Event_.join_room_request_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::Event::JoinRoomRequest& Event::_internal_join_room_request() const {
  return Data_Event_case() == kJoinRoomRequest ? *reinterpret_cast<::Event::JoinRoomRequest*>(_impl_.Data_Event_.join_room_request_) : reinterpret_cast<::Event::JoinRoomRequest&>(::Event::_JoinRoomRequest_default_instance_);
}
inline const ::Event::JoinRoomRequest& Event::join_room_request() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Event.Event.join_room_request)
  return _internal_join_room_request();
}
inline ::Event::JoinRoomRequest* PROTOBUF_NULLABLE Event::unsafe_arena_release_join_room_request() {
  // @@protoc_insertion_point(field_unsafe_arena_release:Event.Event.join_room_request)
  if (Data_Event_case() == kJoinRoomRequest) {
    clear_has_Data_Event();
    auto* temp = reinterpret_cast<::Event::JoinRoomRequest*>(_impl_.Data_Event_.join_room_request_);
    _impl_.Data_Event_.join_room_request_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void Event::unsafe_arena_set_allocated_join_room_request(
    ::Event::JoinRoomRequest* PROTOBUF_NULLABLE value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_Data_Event();
  if (value) {
    set_has_join_room_request();
    _impl_.Data_Event_.join_room_request_ = reinterpret_cast<::google::protobuf::Message*>(value);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Event.Event.join_room_request)
}
inline ::Event::JoinRoomRequest* PROTOBUF_NONNULL Event::_internal_mutable_join_room_request() {
  if (Data_Event_case() != kJoinRoomRequest) {
    clear_Data_Event();
    set_has_join_room_request();
    _impl_.Data_Event_.join_room_request_ = reinterpret_cast<::google::protobuf::Message*>(
        ::google::protobuf::Message::DefaultConstruct<::Event::JoinRoomRequest>(GetArena()));
  }
  return reinterpret_cast<::Event::JoinRoomRequest*>(_impl_.Data_Event_.join_room_request_);
}
inline ::Event::JoinRoomRequest* PROTOBUF_NONNULL Event::mutable_join_room_request()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::Event::JoinRoomRequest* _msg = _internal_mutable_join_room_request();
  // @@protoc_insertion_point(field_mutable:Event.Event.join_room_request)
  return _msg;
}

// .Event.JoinRoomResponse join_room_response = 3;
inline bool Event::has_join_room_response() const {
  return Data_Event_case() == kJoinRoomResponse;
}
inline bool Event::_internal_has_join_room_response() const {
  return Data_Event_case() == kJoinRoomResponse;
}
inline void Event::set_has_join_room_response() {
  _impl_._oneof_case_[0] = kJoinRoomResponse;
}
inline void Event::clear_join_room_response() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (Data_Event_case() == kJoinRoomResponse) {
    if (GetArena() == nullptr) {
      delete _impl_.Data_Event_.join_room_response_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.Data_Event_.join_room_response_);
    }
    clear_has_Data_Event();
  }
}
inline ::Event::JoinRoomResponse* PROTOBUF_NULLABLE Event::release_join_room_response() {
  // @@protoc_insertion_point(field_release:Event.Event.join_room_response)
  if (Data_Event_case() == kJoinRoomResponse) {
    clear_has_Data_Event();
    auto* temp = reinterpret_cast<::Event::JoinRoomResponse*>(_impl_.Data_Event_.join_room_response_);
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.Data_Event_.join_room_response_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::Event::JoinRoomResponse& Event::_internal_join_room_response() const {
  return Data_Event_case() == kJoinRoomResponse ? *reinterpret_cast<::Event::JoinRoomResponse*>(_impl_.Data_Event_.join_room_response_) : reinterpret_cast<::Event::JoinRoomResponse&>(::Event::_JoinRoomResponse_default_instance_);
}
inline const ::Event::JoinRoomResponse& Event::join_room_response() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Event.Event.join_room_response)
  return _internal_join_room_response();
}
inline ::Event::JoinRoomResponse* PROTOBUF_NULLABLE Event::unsafe_arena_release_join_room_response() {
  // @@protoc_insertion_point(field_unsafe_arena_release:Event.Event.join_room_response)
  if (Data_Event_case() == kJoinRoomResponse) {
    clear_has_Data_Event();
    auto* temp = reinterpret_cast<::Event::JoinRoomResponse*>(_impl_.Data_Event_.join_room_response_);
    _impl_.Data_Event_.join_room_response_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void Event::unsafe_arena_set_allocated_join_room_response(
    ::Event::JoinRoomResponse* PROTOBUF_NULLABLE value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_Data_Event();
  if (value) {
    set_has_join_room_response();
    _impl_.Data_Event_.join_room_response_ = reinterpret_cast<::google::protobuf::Message*>(value);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Event.Event.join_room_response)
}
inline ::Event::JoinRoomResponse* PROTOBUF_NONNULL Event::_internal_mutable_join_room_response() {
  if (Data_Event_case() != kJoinRoomResponse) {
    clear_Data_Event();
    set_has_join_room_response();
    _impl_.Data_Event_.join_room_response_ = reinterpret_cast<::google::protobuf::Message*>(
        ::google::protobuf::Message::DefaultConstruct<::Event::JoinRoomResponse>(GetArena()));
  }
  return reinterpret_cast<::Event::JoinRoomResponse*>(_impl_.Data_Event_.join_room_response_);
}
inline ::Event::JoinRoomResponse* PROTOBUF_NONNULL Event::mutable_join_room_response()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::Event::JoinRoomResponse* _msg = _internal_mutable_join_room_response();
  // @@protoc_insertion_point(field_mutable:Event.Event.join_room_response)
  return _msg;
}

// .Event.RoomStatusRequest room_status_request = 4;
inline bool Event::has_room_status_request() const {
  return Data_Event_case() == kRoomStatusRequest;
}
inline bool Event::_internal_has_room_status_request() const {
  return Data_Event_case() == kRoomStatusRequest;
}
inline void Event::set_has_room_status_request() {
  _impl_._oneof_case_[0] = kRoomStatusRequest;
}
inline void Event::clear_room_status_request() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (Data_Event_case() == kRoomStatusRequest) {
    if (GetArena() == nullptr) {
      delete _impl_.Data_Event_.room_status_request_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.Data_Event_.room_status_request_);
    }
    clear_has_Data_Event();
  }
}
inline ::Event::RoomStatusRequest* PROTOBUF_NULLABLE Event::release_room_status_request() {
  // @@protoc_insertion_point(field_release:Event.Event.room_status_request)
  if (Data_Event_case() == kRoomStatusRequest) {
    clear_has_Data_Event();
    auto* temp = reinterpret_cast<::Event::RoomStatusRequest*>(_impl_.Data_Event_.room_status_request_);
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.Data_Event_.room_status_request_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::Event::RoomStatusRequest& Event::_internal_room_status_request() const {
  return Data_Event_case() == kRoomStatusRequest ? *reinterpret_cast<::Event::RoomStatusRequest*>(_impl_.Data_Event_.room_status_request_) : reinterpret_cast<::Event::RoomStatusRequest&>(::Event::_RoomStatusRequest_default_instance_);
}
inline const ::Event::RoomStatusRequest& Event::room_status_request() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Event.Event.room_status_request)
  return _internal_room_status_request();
}
inline ::Event::RoomStatusRequest* PROTOBUF_NULLABLE Event::unsafe_arena_release_room_status_request() {
  // @@protoc_insertion_point(field_unsafe_arena_release:Event.Event.room_status_request)
  if (Data_Event_case() == kRoomStatusRequest) {
    clear_has_Data_Event();
    auto* temp = reinterpret_cast<::Event::RoomStatusRequest*>(_impl_.Data_Event_.room_status_request_);
    _impl_.Data_Event_.room_status_request_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void Event::unsafe_arena_set_allocated_room_status_request(
    ::Event::RoomStatusRequest* PROTOBUF_NULLABLE value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_Data_Event();
  if (value) {
    set_has_room_status_request();
    _impl_.Data_Event_.room_status_request_ = reinterpret_cast<::google::protobuf::Message*>(value);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Event.Event.room_status_request)
}
inline ::Event::RoomStatusRequest* PROTOBUF_NONNULL Event::_internal_mutable_room_status_request() {
  if (Data_Event_case() != kRoomStatusRequest) {
    clear_Data_Event();
    set_has_room_status_request();
    _impl_.Data_Event_.room_status_request_ = reinterpret_cast<::google::protobuf::Message*>(
        ::google::protobuf::Message::DefaultConstruct<::Event::RoomStatusRequest>(GetArena()));
  }
  return reinterpret_cast<::Event::RoomStatusRequest*>(_impl_.Data_Event_.room_status_request_);
}
inline ::Event::RoomStatusRequest* PROTOBUF_NONNULL Event::mutable_room_status_request()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::Event::RoomStatusRequest* _msg = _internal_mutable_room_status_request();
  // @@protoc_insertion_point(field_mutable:Event.Event.room_status_request)
  return _msg;
}

inline bool Event::has_Data_Event() const {
  return Data_Event_case() != DATA_EVENT_NOT_SET;
}
inline void Event::clear_has_Data_Event() {
  _impl_._oneof_case_[0] = DATA_EVENT_NOT_SET;
}
inline Event::DataEventCase Event::Data_Event_case() const {
  return Event::DataEventCase(_impl_._oneof_case_[0]);
}
#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace Event


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // event_5fname_2eproto_2epb_2eh
