// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v6.32.1
// source: event_name.proto

package gateway

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ElementType int32

const (
	ElementType_UNKNOWN_ELEMENT ElementType = 0 // Always start with 0 as a default
	ElementType_WORKER          ElementType = 1
	ElementType_MARINE          ElementType = 2
	ElementType_BASE            ElementType = 3
	ElementType_BARRACK         ElementType = 4
	ElementType_SUPPLY          ElementType = 5
	ElementType_MINERAL         ElementType = 6
)

// Enum value maps for ElementType.
var (
	ElementType_name = map[int32]string{
		0: "UNKNOWN_ELEMENT",
		1: "WORKER",
		2: "MARINE",
		3: "BASE",
		4: "BARRACK",
		5: "SUPPLY",
		6: "MINERAL",
	}
	ElementType_value = map[string]int32{
		"UNKNOWN_ELEMENT": 0,
		"WORKER":          1,
		"MARINE":          2,
		"BASE":            3,
		"BARRACK":         4,
		"SUPPLY":          5,
		"MINERAL":         6,
	}
)

func (x ElementType) Enum() *ElementType {
	p := new(ElementType)
	*p = x
	return p
}

func (x ElementType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ElementType) Descriptor() protoreflect.EnumDescriptor {
	return file_event_name_proto_enumTypes[0].Descriptor()
}

func (ElementType) Type() protoreflect.EnumType {
	return &file_event_name_proto_enumTypes[0]
}

func (x ElementType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ElementType.Descriptor instead.
func (ElementType) EnumDescriptor() ([]byte, []int) {
	return file_event_name_proto_rawDescGZIP(), []int{0}
}

type GameState int32

const (
	GameState_STATE_UNKNOWN    GameState = 0
	GameState_GAME_IN_LOBBY    GameState = 1
	GameState_GAME_IS_STARTING GameState = 2
	GameState_IN_GAME          GameState = 3
	GameState_END_GAME         GameState = 4
)

// Enum value maps for GameState.
var (
	GameState_name = map[int32]string{
		0: "STATE_UNKNOWN",
		1: "GAME_IN_LOBBY",
		2: "GAME_IS_STARTING",
		3: "IN_GAME",
		4: "END_GAME",
	}
	GameState_value = map[string]int32{
		"STATE_UNKNOWN":    0,
		"GAME_IN_LOBBY":    1,
		"GAME_IS_STARTING": 2,
		"IN_GAME":          3,
		"END_GAME":         4,
	}
)

func (x GameState) Enum() *GameState {
	p := new(GameState)
	*p = x
	return p
}

func (x GameState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GameState) Descriptor() protoreflect.EnumDescriptor {
	return file_event_name_proto_enumTypes[1].Descriptor()
}

func (GameState) Type() protoreflect.EnumType {
	return &file_event_name_proto_enumTypes[1]
}

func (x GameState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GameState.Descriptor instead.
func (GameState) EnumDescriptor() ([]byte, []int) {
	return file_event_name_proto_rawDescGZIP(), []int{1}
}

type ColorTeam int32

const (
	ColorTeam_UNKNOW     ColorTeam = 0
	ColorTeam_RED_PROTO  ColorTeam = 1
	ColorTeam_BLUE_PROTO ColorTeam = 2
)

// Enum value maps for ColorTeam.
var (
	ColorTeam_name = map[int32]string{
		0: "UNKNOW",
		1: "RED_PROTO",
		2: "BLUE_PROTO",
	}
	ColorTeam_value = map[string]int32{
		"UNKNOW":     0,
		"RED_PROTO":  1,
		"BLUE_PROTO": 2,
	}
)

func (x ColorTeam) Enum() *ColorTeam {
	p := new(ColorTeam)
	*p = x
	return p
}

func (x ColorTeam) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ColorTeam) Descriptor() protoreflect.EnumDescriptor {
	return file_event_name_proto_enumTypes[2].Descriptor()
}

func (ColorTeam) Type() protoreflect.EnumType {
	return &file_event_name_proto_enumTypes[2]
}

func (x ColorTeam) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ColorTeam.Descriptor instead.
func (ColorTeam) EnumDescriptor() ([]byte, []int) {
	return file_event_name_proto_rawDescGZIP(), []int{2}
}

type Vector2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X int32 `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y int32 `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
}

func (x *Vector2) Reset() {
	*x = Vector2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_event_name_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Vector2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vector2) ProtoMessage() {}

func (x *Vector2) ProtoReflect() protoreflect.Message {
	mi := &file_event_name_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vector2.ProtoReflect.Descriptor instead.
func (*Vector2) Descriptor() ([]byte, []int) {
	return file_event_name_proto_rawDescGZIP(), []int{0}
}

func (x *Vector2) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Vector2) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type Player struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId string     `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Color    *ColorTeam `protobuf:"varint,2,opt,name=color,proto3,enum=Event.ColorTeam,oneof" json:"color,omitempty"`
}

func (x *Player) Reset() {
	*x = Player{}
	if protoimpl.UnsafeEnabled {
		mi := &file_event_name_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player) ProtoMessage() {}

func (x *Player) ProtoReflect() protoreflect.Message {
	mi := &file_event_name_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player.ProtoReflect.Descriptor instead.
func (*Player) Descriptor() ([]byte, []int) {
	return file_event_name_proto_rawDescGZIP(), []int{1}
}

func (x *Player) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *Player) GetColor() ColorTeam {
	if x != nil && x.Color != nil {
		return *x.Color
	}
	return ColorTeam_UNKNOW
}

type MoveElement struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId string   `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	UnitId   string   `protobuf:"bytes,2,opt,name=unit_id,json=unitId,proto3" json:"unit_id,omitempty"`
	OldPos   *Vector2 `protobuf:"bytes,3,opt,name=old_pos,json=oldPos,proto3" json:"old_pos,omitempty"`
	NewPos   *Vector2 `protobuf:"bytes,4,opt,name=new_pos,json=newPos,proto3" json:"new_pos,omitempty"`
}

func (x *MoveElement) Reset() {
	*x = MoveElement{}
	if protoimpl.UnsafeEnabled {
		mi := &file_event_name_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoveElement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveElement) ProtoMessage() {}

func (x *MoveElement) ProtoReflect() protoreflect.Message {
	mi := &file_event_name_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveElement.ProtoReflect.Descriptor instead.
func (*MoveElement) Descriptor() ([]byte, []int) {
	return file_event_name_proto_rawDescGZIP(), []int{2}
}

func (x *MoveElement) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *MoveElement) GetUnitId() string {
	if x != nil {
		return x.UnitId
	}
	return ""
}

func (x *MoveElement) GetOldPos() *Vector2 {
	if x != nil {
		return x.OldPos
	}
	return nil
}

func (x *MoveElement) GetNewPos() *Vector2 {
	if x != nil {
		return x.NewPos
	}
	return nil
}

type Element struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId         string      `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	UnitId           string      `protobuf:"bytes,2,opt,name=unit_id,json=unitId,proto3" json:"unit_id,omitempty"`
	Pos              *Vector2    `protobuf:"bytes,4,opt,name=pos,proto3" json:"pos,omitempty"`
	Size             *Vector2    `protobuf:"bytes,5,opt,name=size,proto3" json:"size,omitempty"`
	ElementType      ElementType `protobuf:"varint,6,opt,name=element_type,json=elementType,proto3,enum=Event.ElementType" json:"element_type,omitempty"`
	CurrentObjective *Vector2    `protobuf:"bytes,7,opt,name=currentObjective,proto3,oneof" json:"currentObjective,omitempty"`
}

func (x *Element) Reset() {
	*x = Element{}
	if protoimpl.UnsafeEnabled {
		mi := &file_event_name_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Element) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Element) ProtoMessage() {}

func (x *Element) ProtoReflect() protoreflect.Message {
	mi := &file_event_name_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Element.ProtoReflect.Descriptor instead.
func (*Element) Descriptor() ([]byte, []int) {
	return file_event_name_proto_rawDescGZIP(), []int{3}
}

func (x *Element) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *Element) GetUnitId() string {
	if x != nil {
		return x.UnitId
	}
	return ""
}

func (x *Element) GetPos() *Vector2 {
	if x != nil {
		return x.Pos
	}
	return nil
}

func (x *Element) GetSize() *Vector2 {
	if x != nil {
		return x.Size
	}
	return nil
}

func (x *Element) GetElementType() ElementType {
	if x != nil {
		return x.ElementType
	}
	return ElementType_UNKNOWN_ELEMENT
}

func (x *Element) GetCurrentObjective() *Vector2 {
	if x != nil {
		return x.CurrentObjective
	}
	return nil
}

type SyncGameState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameState GameState  `protobuf:"varint,1,opt,name=game_state,json=gameState,proto3,enum=Event.GameState" json:"game_state,omitempty"`
	Elements  []*Element `protobuf:"bytes,2,rep,name=elements,proto3" json:"elements,omitempty"` // optional repeated Row rows = 2; // multiple rows → forms a 2D array
}

func (x *SyncGameState) Reset() {
	*x = SyncGameState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_event_name_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncGameState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncGameState) ProtoMessage() {}

func (x *SyncGameState) ProtoReflect() protoreflect.Message {
	mi := &file_event_name_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncGameState.ProtoReflect.Descriptor instead.
func (*SyncGameState) Descriptor() ([]byte, []int) {
	return file_event_name_proto_rawDescGZIP(), []int{4}
}

func (x *SyncGameState) GetGameState() GameState {
	if x != nil {
		return x.GameState
	}
	return GameState_STATE_UNKNOWN
}

func (x *SyncGameState) GetElements() []*Element {
	if x != nil {
		return x.Elements
	}
	return nil
}

type StartGame struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameId string `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
}

func (x *StartGame) Reset() {
	*x = StartGame{}
	if protoimpl.UnsafeEnabled {
		mi := &file_event_name_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartGame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartGame) ProtoMessage() {}

func (x *StartGame) ProtoReflect() protoreflect.Message {
	mi := &file_event_name_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartGame.ProtoReflect.Descriptor instead.
func (*StartGame) Descriptor() ([]byte, []int) {
	return file_event_name_proto_rawDescGZIP(), []int{5}
}

func (x *StartGame) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

type EndGame struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameId string `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
}

func (x *EndGame) Reset() {
	*x = EndGame{}
	if protoimpl.UnsafeEnabled {
		mi := &file_event_name_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EndGame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndGame) ProtoMessage() {}

func (x *EndGame) ProtoReflect() protoreflect.Message {
	mi := &file_event_name_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndGame.ProtoReflect.Descriptor instead.
func (*EndGame) Descriptor() ([]byte, []int) {
	return file_event_name_proto_rawDescGZIP(), []int{6}
}

func (x *EndGame) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

type JoinGame struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameId string `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
}

func (x *JoinGame) Reset() {
	*x = JoinGame{}
	if protoimpl.UnsafeEnabled {
		mi := &file_event_name_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinGame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinGame) ProtoMessage() {}

func (x *JoinGame) ProtoReflect() protoreflect.Message {
	mi := &file_event_name_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinGame.ProtoReflect.Descriptor instead.
func (*JoinGame) Descriptor() ([]byte, []int) {
	return file_event_name_proto_rawDescGZIP(), []int{7}
}

func (x *JoinGame) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

type Event struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameId     string  `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	PlayerInfo *Player `protobuf:"bytes,2,opt,name=player_info,json=playerInfo,proto3" json:"player_info,omitempty"`
	// Types that are assignable to DataEvent:
	//
	//	*Event_MoveElement
	//	*Event_SyncGameState
	//	*Event_EndGame
	//	*Event_StartGame
	//	*Event_JoinGame
	DataEvent isEvent_DataEvent `protobuf_oneof:"data_event"`
}

func (x *Event) Reset() {
	*x = Event{}
	if protoimpl.UnsafeEnabled {
		mi := &file_event_name_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_event_name_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_event_name_proto_rawDescGZIP(), []int{8}
}

func (x *Event) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *Event) GetPlayerInfo() *Player {
	if x != nil {
		return x.PlayerInfo
	}
	return nil
}

func (m *Event) GetDataEvent() isEvent_DataEvent {
	if m != nil {
		return m.DataEvent
	}
	return nil
}

func (x *Event) GetMoveElement() *MoveElement {
	if x, ok := x.GetDataEvent().(*Event_MoveElement); ok {
		return x.MoveElement
	}
	return nil
}

func (x *Event) GetSyncGameState() *SyncGameState {
	if x, ok := x.GetDataEvent().(*Event_SyncGameState); ok {
		return x.SyncGameState
	}
	return nil
}

func (x *Event) GetEndGame() *EndGame {
	if x, ok := x.GetDataEvent().(*Event_EndGame); ok {
		return x.EndGame
	}
	return nil
}

func (x *Event) GetStartGame() *StartGame {
	if x, ok := x.GetDataEvent().(*Event_StartGame); ok {
		return x.StartGame
	}
	return nil
}

func (x *Event) GetJoinGame() *JoinGame {
	if x, ok := x.GetDataEvent().(*Event_JoinGame); ok {
		return x.JoinGame
	}
	return nil
}

type isEvent_DataEvent interface {
	isEvent_DataEvent()
}

type Event_MoveElement struct {
	MoveElement *MoveElement `protobuf:"bytes,3,opt,name=move_element,json=moveElement,proto3,oneof"`
}

type Event_SyncGameState struct {
	SyncGameState *SyncGameState `protobuf:"bytes,4,opt,name=sync_game_state,json=syncGameState,proto3,oneof"`
}

type Event_EndGame struct {
	EndGame *EndGame `protobuf:"bytes,5,opt,name=end_game,json=endGame,proto3,oneof"`
}

type Event_StartGame struct {
	StartGame *StartGame `protobuf:"bytes,6,opt,name=start_game,json=startGame,proto3,oneof"`
}

type Event_JoinGame struct {
	JoinGame *JoinGame `protobuf:"bytes,7,opt,name=join_game,json=joinGame,proto3,oneof"`
}

func (*Event_MoveElement) isEvent_DataEvent() {}

func (*Event_SyncGameState) isEvent_DataEvent() {}

func (*Event_EndGame) isEvent_DataEvent() {}

func (*Event_StartGame) isEvent_DataEvent() {}

func (*Event_JoinGame) isEvent_DataEvent() {}

var File_event_name_proto protoreflect.FileDescriptor

var file_event_name_proto_rawDesc = []byte{
	0x0a, 0x10, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x05, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x22, 0x25, 0x0a, 0x07, 0x56, 0x65, 0x63,
	0x74, 0x6f, 0x72, 0x32, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x79,
	0x22, 0x5c, 0x0a, 0x06, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x12, 0x2b, 0x0a, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x43,
	0x6f, 0x6c, 0x6f, 0x72, 0x54, 0x65, 0x61, 0x6d, 0x48, 0x00, 0x52, 0x05, 0x63, 0x6f, 0x6c, 0x6f,
	0x72, 0x88, 0x01, 0x01, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x22, 0x95,
	0x01, 0x0a, 0x0b, 0x4d, 0x6f, 0x76, 0x65, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x1b,
	0x0a, 0x09, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75,
	0x6e, 0x69, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x6e,
	0x69, 0x74, 0x49, 0x64, 0x12, 0x27, 0x0a, 0x07, 0x6f, 0x6c, 0x64, 0x5f, 0x70, 0x6f, 0x73, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x56, 0x65,
	0x63, 0x74, 0x6f, 0x72, 0x32, 0x52, 0x06, 0x6f, 0x6c, 0x64, 0x50, 0x6f, 0x73, 0x12, 0x27, 0x0a,
	0x07, 0x6e, 0x65, 0x77, 0x5f, 0x70, 0x6f, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e,
	0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x32, 0x52, 0x06,
	0x6e, 0x65, 0x77, 0x50, 0x6f, 0x73, 0x22, 0x92, 0x02, 0x0a, 0x07, 0x45, 0x6c, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x17, 0x0a, 0x07, 0x75, 0x6e, 0x69, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x75, 0x6e, 0x69, 0x74, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x03, 0x70, 0x6f, 0x73, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x56, 0x65,
	0x63, 0x74, 0x6f, 0x72, 0x32, 0x52, 0x03, 0x70, 0x6f, 0x73, 0x12, 0x22, 0x0a, 0x04, 0x73, 0x69,
	0x7a, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x2e, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x32, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x35,
	0x0a, 0x0c, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x45, 0x6c, 0x65,
	0x6d, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0b, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x3f, 0x0a, 0x10, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74,
	0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x76, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0e, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x32, 0x48,
	0x00, 0x52, 0x10, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x69, 0x76, 0x65, 0x88, 0x01, 0x01, 0x42, 0x13, 0x0a, 0x11, 0x5f, 0x63, 0x75, 0x72, 0x72, 0x65,
	0x6e, 0x74, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x76, 0x65, 0x22, 0x6c, 0x0a, 0x0d, 0x53,
	0x79, 0x6e, 0x63, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x2f, 0x0a, 0x0a,
	0x67, 0x61, 0x6d, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x10, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x52, 0x09, 0x67, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x2a, 0x0a,
	0x08, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0e, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52,
	0x08, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x24, 0x0a, 0x09, 0x53, 0x74, 0x61,
	0x72, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x22,
	0x22, 0x0a, 0x07, 0x45, 0x6e, 0x64, 0x47, 0x61, 0x6d, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x67, 0x61,
	0x6d, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x67, 0x61, 0x6d,
	0x65, 0x49, 0x64, 0x22, 0x23, 0x0a, 0x08, 0x4a, 0x6f, 0x69, 0x6e, 0x47, 0x61, 0x6d, 0x65, 0x12,
	0x17, 0x0a, 0x07, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x22, 0xe7, 0x02, 0x0a, 0x05, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x12, 0x2e, 0x0a, 0x0b, 0x70,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0d, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52,
	0x0a, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x37, 0x0a, 0x0c, 0x6d,
	0x6f, 0x76, 0x65, 0x5f, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x12, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x4d, 0x6f, 0x76, 0x65, 0x45, 0x6c,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x0b, 0x6d, 0x6f, 0x76, 0x65, 0x45, 0x6c, 0x65,
	0x6d, 0x65, 0x6e, 0x74, 0x12, 0x3e, 0x0a, 0x0f, 0x73, 0x79, 0x6e, 0x63, 0x5f, 0x67, 0x61, 0x6d,
	0x65, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x53, 0x79, 0x6e, 0x63, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x48, 0x00, 0x52, 0x0d, 0x73, 0x79, 0x6e, 0x63, 0x47, 0x61, 0x6d, 0x65, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x12, 0x2b, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x5f, 0x67, 0x61, 0x6d, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x45,
	0x6e, 0x64, 0x47, 0x61, 0x6d, 0x65, 0x48, 0x00, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x47, 0x61, 0x6d,
	0x65, 0x12, 0x31, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x67, 0x61, 0x6d, 0x65, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x53, 0x74,
	0x61, 0x72, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x48, 0x00, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74,
	0x47, 0x61, 0x6d, 0x65, 0x12, 0x2e, 0x0a, 0x09, 0x6a, 0x6f, 0x69, 0x6e, 0x5f, 0x67, 0x61, 0x6d,
	0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e,
	0x4a, 0x6f, 0x69, 0x6e, 0x47, 0x61, 0x6d, 0x65, 0x48, 0x00, 0x52, 0x08, 0x6a, 0x6f, 0x69, 0x6e,
	0x47, 0x61, 0x6d, 0x65, 0x42, 0x0c, 0x0a, 0x0a, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x65, 0x76, 0x65,
	0x6e, 0x74, 0x2a, 0x6a, 0x0a, 0x0b, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x13, 0x0a, 0x0f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x5f, 0x45, 0x4c, 0x45,
	0x4d, 0x45, 0x4e, 0x54, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x57, 0x4f, 0x52, 0x4b, 0x45, 0x52,
	0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x4d, 0x41, 0x52, 0x49, 0x4e, 0x45, 0x10, 0x02, 0x12, 0x08,
	0x0a, 0x04, 0x42, 0x41, 0x53, 0x45, 0x10, 0x03, 0x12, 0x0b, 0x0a, 0x07, 0x42, 0x41, 0x52, 0x52,
	0x41, 0x43, 0x4b, 0x10, 0x04, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x55, 0x50, 0x50, 0x4c, 0x59, 0x10,
	0x05, 0x12, 0x0b, 0x0a, 0x07, 0x4d, 0x49, 0x4e, 0x45, 0x52, 0x41, 0x4c, 0x10, 0x06, 0x2a, 0x62,
	0x0a, 0x09, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x11, 0x0a, 0x0d, 0x53,
	0x54, 0x41, 0x54, 0x45, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x11,
	0x0a, 0x0d, 0x47, 0x41, 0x4d, 0x45, 0x5f, 0x49, 0x4e, 0x5f, 0x4c, 0x4f, 0x42, 0x42, 0x59, 0x10,
	0x01, 0x12, 0x14, 0x0a, 0x10, 0x47, 0x41, 0x4d, 0x45, 0x5f, 0x49, 0x53, 0x5f, 0x53, 0x54, 0x41,
	0x52, 0x54, 0x49, 0x4e, 0x47, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x49, 0x4e, 0x5f, 0x47, 0x41,
	0x4d, 0x45, 0x10, 0x03, 0x12, 0x0c, 0x0a, 0x08, 0x45, 0x4e, 0x44, 0x5f, 0x47, 0x41, 0x4d, 0x45,
	0x10, 0x04, 0x2a, 0x36, 0x0a, 0x09, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x54, 0x65, 0x61, 0x6d, 0x12,
	0x0a, 0x0a, 0x06, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x52,
	0x45, 0x44, 0x5f, 0x50, 0x52, 0x4f, 0x54, 0x4f, 0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x42, 0x4c,
	0x55, 0x45, 0x5f, 0x50, 0x52, 0x4f, 0x54, 0x4f, 0x10, 0x02, 0x42, 0x0a, 0x5a, 0x08, 0x2f, 0x67,
	0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_event_name_proto_rawDescOnce sync.Once
	file_event_name_proto_rawDescData = file_event_name_proto_rawDesc
)

func file_event_name_proto_rawDescGZIP() []byte {
	file_event_name_proto_rawDescOnce.Do(func() {
		file_event_name_proto_rawDescData = protoimpl.X.CompressGZIP(file_event_name_proto_rawDescData)
	})
	return file_event_name_proto_rawDescData
}

var file_event_name_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_event_name_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_event_name_proto_goTypes = []interface{}{
	(ElementType)(0),      // 0: Event.ElementType
	(GameState)(0),        // 1: Event.GameState
	(ColorTeam)(0),        // 2: Event.ColorTeam
	(*Vector2)(nil),       // 3: Event.Vector2
	(*Player)(nil),        // 4: Event.Player
	(*MoveElement)(nil),   // 5: Event.MoveElement
	(*Element)(nil),       // 6: Event.Element
	(*SyncGameState)(nil), // 7: Event.SyncGameState
	(*StartGame)(nil),     // 8: Event.StartGame
	(*EndGame)(nil),       // 9: Event.EndGame
	(*JoinGame)(nil),      // 10: Event.JoinGame
	(*Event)(nil),         // 11: Event.Event
}
var file_event_name_proto_depIdxs = []int32{
	2,  // 0: Event.Player.color:type_name -> Event.ColorTeam
	3,  // 1: Event.MoveElement.old_pos:type_name -> Event.Vector2
	3,  // 2: Event.MoveElement.new_pos:type_name -> Event.Vector2
	3,  // 3: Event.Element.pos:type_name -> Event.Vector2
	3,  // 4: Event.Element.size:type_name -> Event.Vector2
	0,  // 5: Event.Element.element_type:type_name -> Event.ElementType
	3,  // 6: Event.Element.currentObjective:type_name -> Event.Vector2
	1,  // 7: Event.SyncGameState.game_state:type_name -> Event.GameState
	6,  // 8: Event.SyncGameState.elements:type_name -> Event.Element
	4,  // 9: Event.Event.player_info:type_name -> Event.Player
	5,  // 10: Event.Event.move_element:type_name -> Event.MoveElement
	7,  // 11: Event.Event.sync_game_state:type_name -> Event.SyncGameState
	9,  // 12: Event.Event.end_game:type_name -> Event.EndGame
	8,  // 13: Event.Event.start_game:type_name -> Event.StartGame
	10, // 14: Event.Event.join_game:type_name -> Event.JoinGame
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_event_name_proto_init() }
func file_event_name_proto_init() {
	if File_event_name_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_event_name_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Vector2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_event_name_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Player); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_event_name_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoveElement); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_event_name_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Element); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_event_name_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncGameState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_event_name_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartGame); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_event_name_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EndGame); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_event_name_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinGame); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_event_name_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Event); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_event_name_proto_msgTypes[1].OneofWrappers = []interface{}{}
	file_event_name_proto_msgTypes[3].OneofWrappers = []interface{}{}
	file_event_name_proto_msgTypes[8].OneofWrappers = []interface{}{
		(*Event_MoveElement)(nil),
		(*Event_SyncGameState)(nil),
		(*Event_EndGame)(nil),
		(*Event_StartGame)(nil),
		(*Event_JoinGame)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_event_name_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_event_name_proto_goTypes,
		DependencyIndexes: file_event_name_proto_depIdxs,
		EnumInfos:         file_event_name_proto_enumTypes,
		MessageInfos:      file_event_name_proto_msgTypes,
	}.Build()
	File_event_name_proto = out.File
	file_event_name_proto_rawDesc = nil
	file_event_name_proto_goTypes = nil
	file_event_name_proto_depIdxs = nil
}
