// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v6.32.0
// source: event_name.proto

package gateway

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Player struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UniqueID string `protobuf:"bytes,1,opt,name=uniqueID,proto3" json:"uniqueID,omitempty"`
}

func (x *Player) Reset() {
	*x = Player{}
	if protoimpl.UnsafeEnabled {
		mi := &file_event_name_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player) ProtoMessage() {}

func (x *Player) ProtoReflect() protoreflect.Message {
	mi := &file_event_name_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player.ProtoReflect.Descriptor instead.
func (*Player) Descriptor() ([]byte, []int) {
	return file_event_name_proto_rawDescGZIP(), []int{0}
}

func (x *Player) GetUniqueID() string {
	if x != nil {
		return x.UniqueID
	}
	return ""
}

type JoinRoomRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Room string `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
}

func (x *JoinRoomRequest) Reset() {
	*x = JoinRoomRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_event_name_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRoomRequest) ProtoMessage() {}

func (x *JoinRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_name_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRoomRequest.ProtoReflect.Descriptor instead.
func (*JoinRoomRequest) Descriptor() ([]byte, []int) {
	return file_event_name_proto_rawDescGZIP(), []int{1}
}

func (x *JoinRoomRequest) GetRoom() string {
	if x != nil {
		return x.Room
	}
	return ""
}

type JoinRoomResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Room         string    `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	UniqueID     string    `protobuf:"bytes,2,opt,name=uniqueID,proto3" json:"uniqueID,omitempty"`
	PlayerInRoom []*Player `protobuf:"bytes,3,rep,name=player_in_room,json=playerInRoom,proto3" json:"player_in_room,omitempty"`
}

func (x *JoinRoomResponse) Reset() {
	*x = JoinRoomResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_event_name_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRoomResponse) ProtoMessage() {}

func (x *JoinRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_name_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRoomResponse.ProtoReflect.Descriptor instead.
func (*JoinRoomResponse) Descriptor() ([]byte, []int) {
	return file_event_name_proto_rawDescGZIP(), []int{2}
}

func (x *JoinRoomResponse) GetRoom() string {
	if x != nil {
		return x.Room
	}
	return ""
}

func (x *JoinRoomResponse) GetUniqueID() string {
	if x != nil {
		return x.UniqueID
	}
	return ""
}

func (x *JoinRoomResponse) GetPlayerInRoom() []*Player {
	if x != nil {
		return x.PlayerInRoom
	}
	return nil
}

type RoomStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameStarted bool `protobuf:"varint,1,opt,name=game_started,json=gameStarted,proto3" json:"game_started,omitempty"`
}

func (x *RoomStatusRequest) Reset() {
	*x = RoomStatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_event_name_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomStatusRequest) ProtoMessage() {}

func (x *RoomStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_name_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomStatusRequest.ProtoReflect.Descriptor instead.
func (*RoomStatusRequest) Descriptor() ([]byte, []int) {
	return file_event_name_proto_rawDescGZIP(), []int{3}
}

func (x *RoomStatusRequest) GetGameStarted() bool {
	if x != nil {
		return x.GameStarted
	}
	return false
}

type Event struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Data_Event:
	//
	//	*Event_PlayerData
	//	*Event_JoinRoomRequest
	//	*Event_JoinRoomResponse
	//	*Event_RoomStatusRequest
	Data_Event isEvent_Data_Event `protobuf_oneof:"Data_Event"`
}

func (x *Event) Reset() {
	*x = Event{}
	if protoimpl.UnsafeEnabled {
		mi := &file_event_name_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_event_name_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_event_name_proto_rawDescGZIP(), []int{4}
}

func (m *Event) GetData_Event() isEvent_Data_Event {
	if m != nil {
		return m.Data_Event
	}
	return nil
}

func (x *Event) GetPlayerData() *Player {
	if x, ok := x.GetData_Event().(*Event_PlayerData); ok {
		return x.PlayerData
	}
	return nil
}

func (x *Event) GetJoinRoomRequest() *JoinRoomRequest {
	if x, ok := x.GetData_Event().(*Event_JoinRoomRequest); ok {
		return x.JoinRoomRequest
	}
	return nil
}

func (x *Event) GetJoinRoomResponse() *JoinRoomResponse {
	if x, ok := x.GetData_Event().(*Event_JoinRoomResponse); ok {
		return x.JoinRoomResponse
	}
	return nil
}

func (x *Event) GetRoomStatusRequest() *RoomStatusRequest {
	if x, ok := x.GetData_Event().(*Event_RoomStatusRequest); ok {
		return x.RoomStatusRequest
	}
	return nil
}

type isEvent_Data_Event interface {
	isEvent_Data_Event()
}

type Event_PlayerData struct {
	PlayerData *Player `protobuf:"bytes,1,opt,name=player_data,json=playerData,proto3,oneof"`
}

type Event_JoinRoomRequest struct {
	JoinRoomRequest *JoinRoomRequest `protobuf:"bytes,2,opt,name=join_room_request,json=joinRoomRequest,proto3,oneof"`
}

type Event_JoinRoomResponse struct {
	JoinRoomResponse *JoinRoomResponse `protobuf:"bytes,3,opt,name=join_room_response,json=joinRoomResponse,proto3,oneof"`
}

type Event_RoomStatusRequest struct {
	RoomStatusRequest *RoomStatusRequest `protobuf:"bytes,4,opt,name=room_status_request,json=roomStatusRequest,proto3,oneof"`
}

func (*Event_PlayerData) isEvent_Data_Event() {}

func (*Event_JoinRoomRequest) isEvent_Data_Event() {}

func (*Event_JoinRoomResponse) isEvent_Data_Event() {}

func (*Event_RoomStatusRequest) isEvent_Data_Event() {}

var File_event_name_proto protoreflect.FileDescriptor

var file_event_name_proto_rawDesc = []byte{
	0x0a, 0x10, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x05, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x22, 0x24, 0x0a, 0x06, 0x50, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x49, 0x44, 0x22,
	0x25, 0x0a, 0x0f, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x72, 0x6f, 0x6f, 0x6d, 0x22, 0x77, 0x0a, 0x10, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x6f,
	0x6f, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f,
	0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x6f, 0x6f, 0x6d, 0x12, 0x1a,
	0x0a, 0x08, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x49, 0x44, 0x12, 0x33, 0x0a, 0x0e, 0x70, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x5f, 0x69, 0x6e, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x52, 0x0c, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x52, 0x6f, 0x6f, 0x6d, 0x22,
	0x36, 0x0a, 0x11, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x73, 0x74, 0x61,
	0x72, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x67, 0x61, 0x6d, 0x65,
	0x53, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x22, 0xa2, 0x02, 0x0a, 0x05, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x12, 0x30, 0x0a, 0x0b, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x50,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x48, 0x00, 0x52, 0x0a, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x44,
	0x61, 0x74, 0x61, 0x12, 0x44, 0x0a, 0x11, 0x6a, 0x6f, 0x69, 0x6e, 0x5f, 0x72, 0x6f, 0x6f, 0x6d,
	0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16,
	0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x6f, 0x6f, 0x6d, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x0f, 0x6a, 0x6f, 0x69, 0x6e, 0x52, 0x6f,
	0x6f, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x47, 0x0a, 0x12, 0x6a, 0x6f, 0x69,
	0x6e, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x4a, 0x6f,
	0x69, 0x6e, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00,
	0x52, 0x10, 0x6a, 0x6f, 0x69, 0x6e, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x4a, 0x0a, 0x13, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x18, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x11, 0x72, 0x6f, 0x6f,
	0x6d, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x42, 0x0c,
	0x0a, 0x0a, 0x44, 0x61, 0x74, 0x61, 0x5f, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x42, 0x0a, 0x5a, 0x08,
	0x2f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_event_name_proto_rawDescOnce sync.Once
	file_event_name_proto_rawDescData = file_event_name_proto_rawDesc
)

func file_event_name_proto_rawDescGZIP() []byte {
	file_event_name_proto_rawDescOnce.Do(func() {
		file_event_name_proto_rawDescData = protoimpl.X.CompressGZIP(file_event_name_proto_rawDescData)
	})
	return file_event_name_proto_rawDescData
}

var file_event_name_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_event_name_proto_goTypes = []interface{}{
	(*Player)(nil),            // 0: Event.Player
	(*JoinRoomRequest)(nil),   // 1: Event.JoinRoomRequest
	(*JoinRoomResponse)(nil),  // 2: Event.JoinRoomResponse
	(*RoomStatusRequest)(nil), // 3: Event.RoomStatusRequest
	(*Event)(nil),             // 4: Event.Event
}
var file_event_name_proto_depIdxs = []int32{
	0, // 0: Event.JoinRoomResponse.player_in_room:type_name -> Event.Player
	0, // 1: Event.Event.player_data:type_name -> Event.Player
	1, // 2: Event.Event.join_room_request:type_name -> Event.JoinRoomRequest
	2, // 3: Event.Event.join_room_response:type_name -> Event.JoinRoomResponse
	3, // 4: Event.Event.room_status_request:type_name -> Event.RoomStatusRequest
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_event_name_proto_init() }
func file_event_name_proto_init() {
	if File_event_name_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_event_name_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Player); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_event_name_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinRoomRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_event_name_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinRoomResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_event_name_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomStatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_event_name_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Event); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_event_name_proto_msgTypes[4].OneofWrappers = []interface{}{
		(*Event_PlayerData)(nil),
		(*Event_JoinRoomRequest)(nil),
		(*Event_JoinRoomResponse)(nil),
		(*Event_RoomStatusRequest)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_event_name_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_event_name_proto_goTypes,
		DependencyIndexes: file_event_name_proto_depIdxs,
		MessageInfos:      file_event_name_proto_msgTypes,
	}.Build()
	File_event_name_proto = out.File
	file_event_name_proto_rawDesc = nil
	file_event_name_proto_goTypes = nil
	file_event_name_proto_depIdxs = nil
}
