// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: event_name.proto

package gateway

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ElementType int32

const (
	ElementType_UNKNOWN_ELEMENT ElementType = 0 // Always start with 0 as a default
	ElementType_UNIT            ElementType = 1
	ElementType_BUILDING        ElementType = 2
)

// Enum value maps for ElementType.
var (
	ElementType_name = map[int32]string{
		0: "UNKNOWN_ELEMENT",
		1: "UNIT",
		2: "BUILDING",
	}
	ElementType_value = map[string]int32{
		"UNKNOWN_ELEMENT": 0,
		"UNIT":            1,
		"BUILDING":        2,
	}
)

func (x ElementType) Enum() *ElementType {
	p := new(ElementType)
	*p = x
	return p
}

func (x ElementType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ElementType) Descriptor() protoreflect.EnumDescriptor {
	return file_event_name_proto_enumTypes[0].Descriptor()
}

func (ElementType) Type() protoreflect.EnumType {
	return &file_event_name_proto_enumTypes[0]
}

func (x ElementType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ElementType.Descriptor instead.
func (ElementType) EnumDescriptor() ([]byte, []int) {
	return file_event_name_proto_rawDescGZIP(), []int{0}
}

type GameState int32

const (
	GameState_STATE_UNKNOWN    GameState = 0
	GameState_GAME_IN_LOBBY    GameState = 1
	GameState_GAME_IS_STARTING GameState = 2
	GameState_IN_GAME          GameState = 3
	GameState_END_GAME         GameState = 4
)

// Enum value maps for GameState.
var (
	GameState_name = map[int32]string{
		0: "STATE_UNKNOWN",
		1: "GAME_IN_LOBBY",
		2: "GAME_IS_STARTING",
		3: "IN_GAME",
		4: "END_GAME",
	}
	GameState_value = map[string]int32{
		"STATE_UNKNOWN":    0,
		"GAME_IN_LOBBY":    1,
		"GAME_IS_STARTING": 2,
		"IN_GAME":          3,
		"END_GAME":         4,
	}
)

func (x GameState) Enum() *GameState {
	p := new(GameState)
	*p = x
	return p
}

func (x GameState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GameState) Descriptor() protoreflect.EnumDescriptor {
	return file_event_name_proto_enumTypes[1].Descriptor()
}

func (GameState) Type() protoreflect.EnumType {
	return &file_event_name_proto_enumTypes[1]
}

func (x GameState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GameState.Descriptor instead.
func (GameState) EnumDescriptor() ([]byte, []int) {
	return file_event_name_proto_rawDescGZIP(), []int{1}
}

type ColorTeam int32

const (
	ColorTeam_UNKNOW     ColorTeam = 0
	ColorTeam_RED_PROTO  ColorTeam = 1
	ColorTeam_BLUE_PROTO ColorTeam = 2
)

// Enum value maps for ColorTeam.
var (
	ColorTeam_name = map[int32]string{
		0: "UNKNOW",
		1: "RED_PROTO",
		2: "BLUE_PROTO",
	}
	ColorTeam_value = map[string]int32{
		"UNKNOW":     0,
		"RED_PROTO":  1,
		"BLUE_PROTO": 2,
	}
)

func (x ColorTeam) Enum() *ColorTeam {
	p := new(ColorTeam)
	*p = x
	return p
}

func (x ColorTeam) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ColorTeam) Descriptor() protoreflect.EnumDescriptor {
	return file_event_name_proto_enumTypes[2].Descriptor()
}

func (ColorTeam) Type() protoreflect.EnumType {
	return &file_event_name_proto_enumTypes[2]
}

func (x ColorTeam) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ColorTeam.Descriptor instead.
func (ColorTeam) EnumDescriptor() ([]byte, []int) {
	return file_event_name_proto_rawDescGZIP(), []int{2}
}

type Vector2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vector2) Reset() {
	*x = Vector2{}
	mi := &file_event_name_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vector2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vector2) ProtoMessage() {}

func (x *Vector2) ProtoReflect() protoreflect.Message {
	mi := &file_event_name_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vector2.ProtoReflect.Descriptor instead.
func (*Vector2) Descriptor() ([]byte, []int) {
	return file_event_name_proto_rawDescGZIP(), []int{0}
}

func (x *Vector2) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Vector2) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type Player struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Color         *ColorTeam             `protobuf:"varint,2,opt,name=color,proto3,enum=Event.ColorTeam,oneof" json:"color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Player) Reset() {
	*x = Player{}
	mi := &file_event_name_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player) ProtoMessage() {}

func (x *Player) ProtoReflect() protoreflect.Message {
	mi := &file_event_name_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player.ProtoReflect.Descriptor instead.
func (*Player) Descriptor() ([]byte, []int) {
	return file_event_name_proto_rawDescGZIP(), []int{1}
}

func (x *Player) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *Player) GetColor() ColorTeam {
	if x != nil && x.Color != nil {
		return *x.Color
	}
	return ColorTeam_UNKNOW
}

type MoveElement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	UnitId        string                 `protobuf:"bytes,2,opt,name=unit_id,json=unitId,proto3" json:"unit_id,omitempty"`
	OldPos        *Vector2               `protobuf:"bytes,3,opt,name=old_pos,json=oldPos,proto3" json:"old_pos,omitempty"`
	NewPos        *Vector2               `protobuf:"bytes,4,opt,name=new_pos,json=newPos,proto3" json:"new_pos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveElement) Reset() {
	*x = MoveElement{}
	mi := &file_event_name_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveElement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveElement) ProtoMessage() {}

func (x *MoveElement) ProtoReflect() protoreflect.Message {
	mi := &file_event_name_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveElement.ProtoReflect.Descriptor instead.
func (*MoveElement) Descriptor() ([]byte, []int) {
	return file_event_name_proto_rawDescGZIP(), []int{2}
}

func (x *MoveElement) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *MoveElement) GetUnitId() string {
	if x != nil {
		return x.UnitId
	}
	return ""
}

func (x *MoveElement) GetOldPos() *Vector2 {
	if x != nil {
		return x.OldPos
	}
	return nil
}

func (x *MoveElement) GetNewPos() *Vector2 {
	if x != nil {
		return x.NewPos
	}
	return nil
}

type Element struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PlayerId         string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	UnitId           string                 `protobuf:"bytes,2,opt,name=unit_id,json=unitId,proto3" json:"unit_id,omitempty"`
	Pos              *Vector2               `protobuf:"bytes,4,opt,name=pos,proto3" json:"pos,omitempty"`
	Size             *Vector2               `protobuf:"bytes,5,opt,name=size,proto3" json:"size,omitempty"`
	ElementType      ElementType            `protobuf:"varint,6,opt,name=element_type,json=elementType,proto3,enum=Event.ElementType" json:"element_type,omitempty"`
	CurrentObjective *Vector2               `protobuf:"bytes,7,opt,name=currentObjective,proto3,oneof" json:"currentObjective,omitempty"`
	Team             ColorTeam              `protobuf:"varint,8,opt,name=team,proto3,enum=Event.ColorTeam" json:"team,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Element) Reset() {
	*x = Element{}
	mi := &file_event_name_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Element) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Element) ProtoMessage() {}

func (x *Element) ProtoReflect() protoreflect.Message {
	mi := &file_event_name_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Element.ProtoReflect.Descriptor instead.
func (*Element) Descriptor() ([]byte, []int) {
	return file_event_name_proto_rawDescGZIP(), []int{3}
}

func (x *Element) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *Element) GetUnitId() string {
	if x != nil {
		return x.UnitId
	}
	return ""
}

func (x *Element) GetPos() *Vector2 {
	if x != nil {
		return x.Pos
	}
	return nil
}

func (x *Element) GetSize() *Vector2 {
	if x != nil {
		return x.Size
	}
	return nil
}

func (x *Element) GetElementType() ElementType {
	if x != nil {
		return x.ElementType
	}
	return ElementType_UNKNOWN_ELEMENT
}

func (x *Element) GetCurrentObjective() *Vector2 {
	if x != nil {
		return x.CurrentObjective
	}
	return nil
}

func (x *Element) GetTeam() ColorTeam {
	if x != nil {
		return x.Team
	}
	return ColorTeam_UNKNOW
}

type SyncGameState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameState     GameState              `protobuf:"varint,1,opt,name=game_state,json=gameState,proto3,enum=Event.GameState" json:"game_state,omitempty"`
	Elements      []*Element             `protobuf:"bytes,2,rep,name=elements,proto3" json:"elements,omitempty"`
	Building      []*Element             `protobuf:"bytes,3,rep,name=building,proto3" json:"building,omitempty"` // optional repeated Row rows = 2; // multiple rows → forms a 2D array
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncGameState) Reset() {
	*x = SyncGameState{}
	mi := &file_event_name_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncGameState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncGameState) ProtoMessage() {}

func (x *SyncGameState) ProtoReflect() protoreflect.Message {
	mi := &file_event_name_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncGameState.ProtoReflect.Descriptor instead.
func (*SyncGameState) Descriptor() ([]byte, []int) {
	return file_event_name_proto_rawDescGZIP(), []int{4}
}

func (x *SyncGameState) GetGameState() GameState {
	if x != nil {
		return x.GameState
	}
	return GameState_STATE_UNKNOWN
}

func (x *SyncGameState) GetElements() []*Element {
	if x != nil {
		return x.Elements
	}
	return nil
}

func (x *SyncGameState) GetBuilding() []*Element {
	if x != nil {
		return x.Building
	}
	return nil
}

type StartGame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        string                 `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartGame) Reset() {
	*x = StartGame{}
	mi := &file_event_name_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartGame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartGame) ProtoMessage() {}

func (x *StartGame) ProtoReflect() protoreflect.Message {
	mi := &file_event_name_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartGame.ProtoReflect.Descriptor instead.
func (*StartGame) Descriptor() ([]byte, []int) {
	return file_event_name_proto_rawDescGZIP(), []int{5}
}

func (x *StartGame) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

type EndGame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        string                 `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndGame) Reset() {
	*x = EndGame{}
	mi := &file_event_name_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndGame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndGame) ProtoMessage() {}

func (x *EndGame) ProtoReflect() protoreflect.Message {
	mi := &file_event_name_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndGame.ProtoReflect.Descriptor instead.
func (*EndGame) Descriptor() ([]byte, []int) {
	return file_event_name_proto_rawDescGZIP(), []int{6}
}

func (x *EndGame) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

type JoinGame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinGame) Reset() {
	*x = JoinGame{}
	mi := &file_event_name_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinGame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinGame) ProtoMessage() {}

func (x *JoinGame) ProtoReflect() protoreflect.Message {
	mi := &file_event_name_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinGame.ProtoReflect.Descriptor instead.
func (*JoinGame) Descriptor() ([]byte, []int) {
	return file_event_name_proto_rawDescGZIP(), []int{7}
}

type AttackElement struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	AttackingElementId string                 `protobuf:"bytes,1,opt,name=attacking_element_id,json=attackingElementId,proto3" json:"attacking_element_id,omitempty"`
	AttackedElementId  string                 `protobuf:"bytes,2,opt,name=attacked_element_id,json=attackedElementId,proto3" json:"attacked_element_id,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AttackElement) Reset() {
	*x = AttackElement{}
	mi := &file_event_name_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttackElement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttackElement) ProtoMessage() {}

func (x *AttackElement) ProtoReflect() protoreflect.Message {
	mi := &file_event_name_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttackElement.ProtoReflect.Descriptor instead.
func (*AttackElement) Descriptor() ([]byte, []int) {
	return file_event_name_proto_rawDescGZIP(), []int{8}
}

func (x *AttackElement) GetAttackingElementId() string {
	if x != nil {
		return x.AttackingElementId
	}
	return ""
}

func (x *AttackElement) GetAttackedElementId() string {
	if x != nil {
		return x.AttackedElementId
	}
	return ""
}

type Event struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	GameId     string                 `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	PlayerInfo *Player                `protobuf:"bytes,2,opt,name=player_info,json=playerInfo,proto3" json:"player_info,omitempty"`
	// Types that are valid to be assigned to DataEvent:
	//
	//	*Event_MoveElement
	//	*Event_SyncGameState
	//	*Event_EndGame
	//	*Event_StartGame
	//	*Event_JoinGame
	//	*Event_AttackElement
	DataEvent     isEvent_DataEvent `protobuf_oneof:"data_event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_event_name_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_event_name_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_event_name_proto_rawDescGZIP(), []int{9}
}

func (x *Event) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *Event) GetPlayerInfo() *Player {
	if x != nil {
		return x.PlayerInfo
	}
	return nil
}

func (x *Event) GetDataEvent() isEvent_DataEvent {
	if x != nil {
		return x.DataEvent
	}
	return nil
}

func (x *Event) GetMoveElement() *MoveElement {
	if x != nil {
		if x, ok := x.DataEvent.(*Event_MoveElement); ok {
			return x.MoveElement
		}
	}
	return nil
}

func (x *Event) GetSyncGameState() *SyncGameState {
	if x != nil {
		if x, ok := x.DataEvent.(*Event_SyncGameState); ok {
			return x.SyncGameState
		}
	}
	return nil
}

func (x *Event) GetEndGame() *EndGame {
	if x != nil {
		if x, ok := x.DataEvent.(*Event_EndGame); ok {
			return x.EndGame
		}
	}
	return nil
}

func (x *Event) GetStartGame() *StartGame {
	if x != nil {
		if x, ok := x.DataEvent.(*Event_StartGame); ok {
			return x.StartGame
		}
	}
	return nil
}

func (x *Event) GetJoinGame() *JoinGame {
	if x != nil {
		if x, ok := x.DataEvent.(*Event_JoinGame); ok {
			return x.JoinGame
		}
	}
	return nil
}

func (x *Event) GetAttackElement() *AttackElement {
	if x != nil {
		if x, ok := x.DataEvent.(*Event_AttackElement); ok {
			return x.AttackElement
		}
	}
	return nil
}

type isEvent_DataEvent interface {
	isEvent_DataEvent()
}

type Event_MoveElement struct {
	MoveElement *MoveElement `protobuf:"bytes,3,opt,name=move_element,json=moveElement,proto3,oneof"`
}

type Event_SyncGameState struct {
	SyncGameState *SyncGameState `protobuf:"bytes,4,opt,name=sync_game_state,json=syncGameState,proto3,oneof"`
}

type Event_EndGame struct {
	EndGame *EndGame `protobuf:"bytes,5,opt,name=end_game,json=endGame,proto3,oneof"`
}

type Event_StartGame struct {
	StartGame *StartGame `protobuf:"bytes,6,opt,name=start_game,json=startGame,proto3,oneof"`
}

type Event_JoinGame struct {
	JoinGame *JoinGame `protobuf:"bytes,7,opt,name=join_game,json=joinGame,proto3,oneof"`
}

type Event_AttackElement struct {
	AttackElement *AttackElement `protobuf:"bytes,8,opt,name=attack_element,json=attackElement,proto3,oneof"`
}

func (*Event_MoveElement) isEvent_DataEvent() {}

func (*Event_SyncGameState) isEvent_DataEvent() {}

func (*Event_EndGame) isEvent_DataEvent() {}

func (*Event_StartGame) isEvent_DataEvent() {}

func (*Event_JoinGame) isEvent_DataEvent() {}

func (*Event_AttackElement) isEvent_DataEvent() {}

var File_event_name_proto protoreflect.FileDescriptor

const file_event_name_proto_rawDesc = "" +
	"\n" +
	"\x10event_name.proto\x12\x05Event\"%\n" +
	"\aVector2\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\"\\\n" +
	"\x06Player\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12+\n" +
	"\x05color\x18\x02 \x01(\x0e2\x10.Event.ColorTeamH\x00R\x05color\x88\x01\x01B\b\n" +
	"\x06_color\"\x95\x01\n" +
	"\vMoveElement\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x17\n" +
	"\aunit_id\x18\x02 \x01(\tR\x06unitId\x12'\n" +
	"\aold_pos\x18\x03 \x01(\v2\x0e.Event.Vector2R\x06oldPos\x12'\n" +
	"\anew_pos\x18\x04 \x01(\v2\x0e.Event.Vector2R\x06newPos\"\xb8\x02\n" +
	"\aElement\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x17\n" +
	"\aunit_id\x18\x02 \x01(\tR\x06unitId\x12 \n" +
	"\x03pos\x18\x04 \x01(\v2\x0e.Event.Vector2R\x03pos\x12\"\n" +
	"\x04size\x18\x05 \x01(\v2\x0e.Event.Vector2R\x04size\x125\n" +
	"\felement_type\x18\x06 \x01(\x0e2\x12.Event.ElementTypeR\velementType\x12?\n" +
	"\x10currentObjective\x18\a \x01(\v2\x0e.Event.Vector2H\x00R\x10currentObjective\x88\x01\x01\x12$\n" +
	"\x04team\x18\b \x01(\x0e2\x10.Event.ColorTeamR\x04teamB\x13\n" +
	"\x11_currentObjective\"\x98\x01\n" +
	"\rSyncGameState\x12/\n" +
	"\n" +
	"game_state\x18\x01 \x01(\x0e2\x10.Event.GameStateR\tgameState\x12*\n" +
	"\belements\x18\x02 \x03(\v2\x0e.Event.ElementR\belements\x12*\n" +
	"\bbuilding\x18\x03 \x03(\v2\x0e.Event.ElementR\bbuilding\"$\n" +
	"\tStartGame\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\tR\x06gameId\"\"\n" +
	"\aEndGame\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\tR\x06gameId\"\n" +
	"\n" +
	"\bJoinGame\"q\n" +
	"\rAttackElement\x120\n" +
	"\x14attacking_element_id\x18\x01 \x01(\tR\x12attackingElementId\x12.\n" +
	"\x13attacked_element_id\x18\x02 \x01(\tR\x11attackedElementId\"\xa6\x03\n" +
	"\x05Event\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\tR\x06gameId\x12.\n" +
	"\vplayer_info\x18\x02 \x01(\v2\r.Event.PlayerR\n" +
	"playerInfo\x127\n" +
	"\fmove_element\x18\x03 \x01(\v2\x12.Event.MoveElementH\x00R\vmoveElement\x12>\n" +
	"\x0fsync_game_state\x18\x04 \x01(\v2\x14.Event.SyncGameStateH\x00R\rsyncGameState\x12+\n" +
	"\bend_game\x18\x05 \x01(\v2\x0e.Event.EndGameH\x00R\aendGame\x121\n" +
	"\n" +
	"start_game\x18\x06 \x01(\v2\x10.Event.StartGameH\x00R\tstartGame\x12.\n" +
	"\tjoin_game\x18\a \x01(\v2\x0f.Event.JoinGameH\x00R\bjoinGame\x12=\n" +
	"\x0eattack_element\x18\b \x01(\v2\x14.Event.AttackElementH\x00R\rattackElementB\f\n" +
	"\n" +
	"data_event*:\n" +
	"\vElementType\x12\x13\n" +
	"\x0fUNKNOWN_ELEMENT\x10\x00\x12\b\n" +
	"\x04UNIT\x10\x01\x12\f\n" +
	"\bBUILDING\x10\x02*b\n" +
	"\tGameState\x12\x11\n" +
	"\rSTATE_UNKNOWN\x10\x00\x12\x11\n" +
	"\rGAME_IN_LOBBY\x10\x01\x12\x14\n" +
	"\x10GAME_IS_STARTING\x10\x02\x12\v\n" +
	"\aIN_GAME\x10\x03\x12\f\n" +
	"\bEND_GAME\x10\x04*6\n" +
	"\tColorTeam\x12\n" +
	"\n" +
	"\x06UNKNOW\x10\x00\x12\r\n" +
	"\tRED_PROTO\x10\x01\x12\x0e\n" +
	"\n" +
	"BLUE_PROTO\x10\x02B\n" +
	"Z\b/gatewayb\x06proto3"

var (
	file_event_name_proto_rawDescOnce sync.Once
	file_event_name_proto_rawDescData []byte
)

func file_event_name_proto_rawDescGZIP() []byte {
	file_event_name_proto_rawDescOnce.Do(func() {
		file_event_name_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_event_name_proto_rawDesc), len(file_event_name_proto_rawDesc)))
	})
	return file_event_name_proto_rawDescData
}

var file_event_name_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_event_name_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_event_name_proto_goTypes = []any{
	(ElementType)(0),      // 0: Event.ElementType
	(GameState)(0),        // 1: Event.GameState
	(ColorTeam)(0),        // 2: Event.ColorTeam
	(*Vector2)(nil),       // 3: Event.Vector2
	(*Player)(nil),        // 4: Event.Player
	(*MoveElement)(nil),   // 5: Event.MoveElement
	(*Element)(nil),       // 6: Event.Element
	(*SyncGameState)(nil), // 7: Event.SyncGameState
	(*StartGame)(nil),     // 8: Event.StartGame
	(*EndGame)(nil),       // 9: Event.EndGame
	(*JoinGame)(nil),      // 10: Event.JoinGame
	(*AttackElement)(nil), // 11: Event.AttackElement
	(*Event)(nil),         // 12: Event.Event
}
var file_event_name_proto_depIdxs = []int32{
	2,  // 0: Event.Player.color:type_name -> Event.ColorTeam
	3,  // 1: Event.MoveElement.old_pos:type_name -> Event.Vector2
	3,  // 2: Event.MoveElement.new_pos:type_name -> Event.Vector2
	3,  // 3: Event.Element.pos:type_name -> Event.Vector2
	3,  // 4: Event.Element.size:type_name -> Event.Vector2
	0,  // 5: Event.Element.element_type:type_name -> Event.ElementType
	3,  // 6: Event.Element.currentObjective:type_name -> Event.Vector2
	2,  // 7: Event.Element.team:type_name -> Event.ColorTeam
	1,  // 8: Event.SyncGameState.game_state:type_name -> Event.GameState
	6,  // 9: Event.SyncGameState.elements:type_name -> Event.Element
	6,  // 10: Event.SyncGameState.building:type_name -> Event.Element
	4,  // 11: Event.Event.player_info:type_name -> Event.Player
	5,  // 12: Event.Event.move_element:type_name -> Event.MoveElement
	7,  // 13: Event.Event.sync_game_state:type_name -> Event.SyncGameState
	9,  // 14: Event.Event.end_game:type_name -> Event.EndGame
	8,  // 15: Event.Event.start_game:type_name -> Event.StartGame
	10, // 16: Event.Event.join_game:type_name -> Event.JoinGame
	11, // 17: Event.Event.attack_element:type_name -> Event.AttackElement
	18, // [18:18] is the sub-list for method output_type
	18, // [18:18] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_event_name_proto_init() }
func file_event_name_proto_init() {
	if File_event_name_proto != nil {
		return
	}
	file_event_name_proto_msgTypes[1].OneofWrappers = []any{}
	file_event_name_proto_msgTypes[3].OneofWrappers = []any{}
	file_event_name_proto_msgTypes[9].OneofWrappers = []any{
		(*Event_MoveElement)(nil),
		(*Event_SyncGameState)(nil),
		(*Event_EndGame)(nil),
		(*Event_StartGame)(nil),
		(*Event_JoinGame)(nil),
		(*Event_AttackElement)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_event_name_proto_rawDesc), len(file_event_name_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_event_name_proto_goTypes,
		DependencyIndexes: file_event_name_proto_depIdxs,
		EnumInfos:         file_event_name_proto_enumTypes,
		MessageInfos:      file_event_name_proto_msgTypes,
	}.Build()
	File_event_name_proto = out.File
	file_event_name_proto_goTypes = nil
	file_event_name_proto_depIdxs = nil
}
